### ISSUE TITLE
50 character password works in cli wallet but not in gui

### ISSUE THREAD

**Issue by tikwanleap** [monero-project/monero-gui#653] opened 2017-03-30 22:44 UTC
I have a 50 character password that works in cli wallet but not in gui.

I tested in the latest versions of both cli and gui (0.10.3.1) on Windows 10 64-bit.

**Comment by medusadigital** [comment] 2017-08-07 21:19
sounds like a possible bug. needs investigation

+bug

**Comment by dEBRUYNE-1** [comment] 2017-12-13 11:09
Does it contain a space?

**Comment by tikwanleap** [comment] 2017-12-13 22:24
It does not. But it does contain accented characters (non-ASCII).

**Comment by dEBRUYNE-1** [comment] 2017-12-14 14:57
Does it contain parentheses as well?

**Comment by tikwanleap** [comment] 2017-12-14 17:43
Yes it contains parentheses.

**Comment by skftn** [comment] 2018-01-11 13:15
Related to #199 #758 #820 and eventually https://github.com/monero-project/monero/issues/1390

**Comment by medusadigital** [comment] 2018-01-11 13:44
will be directly fixed in wallet2 API: https://github.com/monero-project/monero/issues/1390

closing here. 

thanks for report

**Comment by medusadigital** [comment] 2018-01-11 13:45
+duplicate

**Comment by skftn** [comment] 2018-01-11 14:12
Using GUI **Monero 'Helium Hydra' (v0.11.1.0-release)**:

- Create wallet
- Password `Á' ` (accented, parenthesis, space)
- Close GUI

Testing in the CLI:

- `./monero-wallet-cli --testnet --wallet-file="/home/dsc/Monero/wallets/accent_test5/accent_test5.keys"`
- password works, wallet opened

Testing in the GUI:
- `./monero-wallet-gui --testnet`
- Enter password `Á' `
- password works, wallet opened

Can't reproduce bug.

**Comment by medusadigital** [comment] 2018-01-11 14:16
+invalid

**Comment by tikwanleap** [comment] 2018-01-11 21:24
I just tested again with v0.11.1.0 and it still not working. The password is 50 characters long so skftn's test case may need to be modifed to use a 50 character long password with accents, parenthsis, brackets etc.

**Comment by tikwanleap** [comment] 2018-01-11 21:31
Ok, here is a test case where I was able to use the password in the cli but not in the gui. This is all using v0.11.1.0 for both.

password:
¥mùh§I¡|

**Comment by danrmiller** [comment] 2018-04-05 20:02
-invalid

**Comment by xiphon** [comment] 2018-11-06 01:14
> Ok, here is a test case where I was able to use the password in the CLI but still not working in the GUI. This is all using v0.11.1.0 for both.
> 
> password:
> ¥mùh§I¡|
> 
> Also, I created the wallet in CLI. This is different from skftn's test case where it is created in the GUI.

Can't reproduce this one. @tikwanleap , could you check the latest build?

**Comment by dEBRUYNE-1** [comment] 2018-11-11 16:00
+resolved

**Closed** 2018-11-11 16:09 UTC
Labels: bug, resolved
