### ISSUE TITLE
Monero GUI cannot communicate with Ledger on macOS

### ISSUE THREAD

**Issue by t-anon** [monero-project/monero-gui#3494] opened 2021-05-22 00:42 UTC
- GUI 0.17.2 
- Ledger 1.3.0 w/ Monero 1.7.7
- macOS 11.3.1 (M1 chip)

The Monero application on the Ledger immediately quits if the Monero GUI wallet attempts to communicate with it.

The issue began after updating the GUI to 0.17.2  and the Ledger to 1.3.0.

**Comment by selsta** [comment] 2021-05-25 03:31
Is this a Ledger Nano X?

**Comment by selsta** [comment] 2021-05-25 03:39
There does not seem to exit a Monero 1.7.7 version according to https://github.com/LedgerHQ/app-monero/releases

**Comment by t-anon** [comment] 2021-06-03 05:13
@selsta The issue kind of fixed itself after I cleaned out monero-wallet-gui from my laptop and re-installed. Not sure what the root cause was. 

Monero 1.7.7 definitely exists. From Ledger Manager:

<img width="263" alt="Screen Shot 2021-06-03 at 1 12 30 AM" src="https://user-images.githubusercontent.com/82717986/120590630-d4913280-c408-11eb-85b9-435f611d859d.png">

**Comment by selsta** [comment] 2021-06-03 05:14
Thanks for the update. Closing as the issue is resolved.

**Closed by selsta** 2021-06-03 05:14 UTC
