### ISSUE TITLE
"Spendable Funds"

### ISSUE THREAD

**Issue by pullup** [monero-project/monero-gui#3116] opened 2020-09-27 17:52 UTC
Is there no way to disable this child lock "spendable funds" stuff? Incredibly annoying. 
It even makes my entire balance unspendable when I send one transaction outwards, how on Earth does that make sense?

**Comment by rating89us** [comment] 2020-10-02 22:12
No, it's a privacy feature that protects you from spending the same output multiple times in a short period of time, which would compromise your privacy.

If you don't want this to happen anymore, you should send multiple transactions to your wallet, which will create multiple outputs. This way when you spend one output, your wallet won't have the entire balance locked.

**Comment by pullup** [comment] 2020-10-04 22:06
> No, it's a privacy feature that protects you from spending the same output multiple times in a short period of time, which would compromise your privacy.
> 
> If you don't want this to happen anymore, you should send multiple transactions to your wallet, which will create multiple outputs. This way when you spend one output, your wallet won't have the entire balance locked.

Have you not considered the merchant application where their concern is for their client's privacy and not their own? Not everyone using XMR is in it for their own privacy, some just want to enable their customers to have total privacy.

**Comment by xiphon** [comment] 2020-10-04 22:27
Duplicate of https://github.com/monero-project/monero/issues/5810 where you'll find useful info/links, feel free to continue the discussion there

**Closed by xiphon** 2020-10-04 22:27 UTC
