### ISSUE TITLE
I am missing (not seeing) some transactions to (in) the CLI

### ISSUE THREAD

**Issue by GongSuiLi** [monero-project/monero-gui#3479] opened 2021-05-13 03:43 UTC
I encountered a more urgent problem. Use monero-wallet-rpc --configfile to query all transactions in my own wallet, use monero-wallet-cli to create a hot wallet, and use show_transfer txid to return that the transaction does not exist, and only some transactions exist in rpc results. This problem means that the balance of monero-wallet-rpc is greater than the balance of monero-wallet-cli, and there are more transactions. I don't know the reason. I always have the same problem when I try to use the latest version of v0.17.2.0. I would like to ask you to help me. 
I am very worried about the loss of assets. I can check these transactions using rpc, but there is no such transaction created by using cli. I have tried several times

**Comment by selsta** [comment] 2021-05-13 05:16
Which restore height did you set? Do you use subaddresses?

**Comment by GongSuiLi** [comment] 2021-05-13 06:17
> Which restore height did you set? Do you use subaddresses?

I deleted the viewWallet file and recreated it. The command line height defaults to 0. I used  subaddress, but most of the subaddress transactions exist. Only some transactions do not exist in the cli. These transactions can be queried by rpc. You can also find it in the browser

**Comment by selsta** [comment] 2021-05-13 17:23
One thing you can try is to add --subaddress-lookahead 200:1000, in case the issue is related to subaddress lookahead.

Also if you generate a wallet only from view key you won't see outgoing transactions, only incoming and change transactions. Are the missing transactions outgoing transactions?

**Comment by moneromooo-monero** [comment] 2021-05-13 17:28
Did you properly export/import outputs and key images on that hot wallet ? The hot wallet will otherwise not know the key images of your outputs, and will not see any tx spending them without change (ie, sweep txes).

**Comment by GongSuiLi** [comment] 2021-05-14 02:58
> One thing you can try is to add --subaddress-lookahead 200:1000, in case the issue is related to subaddress lookahead.
> 
> Also if you generate a wallet only from view key you won't see outgoing transactions, only incoming and change transactions. Are the missing transactions outgoing transactions?

The transactions I mentioned are incoming transactions, I want to enter #monero-dev to communicate with you directly, how to open the chat room permissions

**Comment by GongSuiLi** [comment] 2021-05-14 03:00
> Did you properly export/import outputs and key images on that hot wallet ? The hot wallet will otherwise not know the key images of your outputs, and will not see any tx spending them without change (ie, sweep txes).

Because the transactions I'm talking about are incoming transactions, I think it has nothing to do with exports/import outputs and keyImages

**Comment by selsta** [comment] 2021-05-14 03:00
@GongSuiLi What is your matrix username?

**Comment by selsta** [comment] 2021-05-17 20:03
Closing as the issue was resolved.

**Closed by selsta** 2021-05-17 20:03 UTC
