### ISSUE TITLE
GUI doesn't run smooth

### ISSUE THREAD

**Issue by ghost** [monero-project/monero-gui#950] opened 2017-11-12 00:13 UTC
I notice the GUI does not run smooth sometimes, for example when I click on something in the menu. It hangs then and needs some seconds to react to the event. I also notice this when using a new installed OS. It seems something is blocking the GUI process sometimes.

Does anyone also noticed this behaviour?

**Comment by skftn** [comment] 2017-11-12 00:33
Someone correct me if I'm wrong; this happens when the GUI is syncing the blockchain. I think an effort had been made to make the GUI more responsive but I am not sure if it is merged into a release yet.

**Comment by dEBRUYNE-1** [comment] 2017-11-12 14:25
Do you have a relatively older system? If so, could you try adding this line in the daemon startup flags box:

`--max-concurrency 1 --limit-rate 500 --block-sync-size 5`

**Comment by Schnoffel** [comment] 2017-11-12 14:28
No, it is a powerful and up-to-date system :)

**Comment by ITwrx** [comment] 2017-12-31 03:26
you might check your cpu usage. my layman's understanding is that cryptonight is expensive(resource usage wise) when verifying, by design, so when you're trying to sync it maxes out the cpu. this makes the gui slow to respond. when it gets done syncing i bet the gui is back to normal responsiveness.

**Comment by SleepswithGators** [comment] 2018-02-22 00:37
Does the wallet need to restart in order to make changes?

**Comment by ITwrx** [comment] 2018-02-22 00:40
@SleepswithGators no, but if you want it to respond to you, it may need to be completely done syncing.

**Comment by dEBRUYNE-1** [comment] 2019-07-04 06:57
This should be fixed in GUI v0.14.1.0, as xiphon added a lot of optimizations in this regard.

**Comment by dEBRUYNE-1** [comment] 2019-07-04 06:58
+resolved

**Closed** 2019-07-04 07:36 UTC
Labels: resolved
