### ISSUE TITLE
Submit each Monero build to VirusTotal as early as possible

### ISSUE THREAD

**Issue by mcgroarty** [monero-project/monero-gui#2753] opened 2020-01-29 22:23 UTC
There are numerous previous issues which talk about antivirus engine false positives.

Consider submitting each Monero build to VirusTotal as early as possible. This accomplishes a few things:

1. It tells you which antivirus engines produce false positives

2. It tells the antivirus producers when their engine is out of sync with others' engines (Google now owns VirusTotal, and they share findings with participating engines)

3. VirusTotal result pages give you something to point at when communicating with antivirus vendors and end users

In my own experience shipping a commercial software product, we get a lot more traction on av vendor tickets when we provide a link to a VirusTotal scan where that vendor is a clear outlier.

Early uploads also mean that the antivirus vendors have an earlier opportunity to begin analysis. Often they clear false positives inside of a few days.

**Comment by selsta** [comment] 2020-01-31 14:18
Does VirusTotal handle archives or does every binary have to get uploaded separately?

**Comment by mcgroarty** [comment] 2020-01-31 20:16
It accepts archives in some formats. Most engines will not look at the tarred bz2 archive. But as best I can tell all engines will look at the contents of a zip file.

They also have an API which can be used to submit individual files. It requires that a user obtain a free API key, although the user must accept some terms and conditions to do so. This could be incorporated into the build scripts as an extra build option or alternative target.

**Comment by selsta** [comment] 2022-03-16 19:51
I'll close this as this is more information and not a bug report :) Will try to think about uploading the archives to virustotal for the next release.

**Closed by selsta** 2022-03-16 19:51 UTC
