### ISSUE TITLE
Button for deleting p2pstate.bin

### ISSUE THREAD

**Issue by scoobybejesus** [monero-project/monero-gui#892] opened 2017-09-26 21:58 UTC
Ideally, in the future, there will be no need for this.  But there seem to be a lot of support requests that require people deleting p2pstate.bin.  This file is in a hidden folder.  Newbies can't find it.  A simple fix of "close the GUI, delete p2pstate.bin, and restart the GUI" turns into several hours of going back and forth on reddit.  A button would simplify solving this issue massively.

**Comment by QuickBASIC** [comment] 2017-10-01 04:38
How about a batch file in the program directory (Windows) or sh (Linux) that does a taskill and deletes the file? I don't like the idea of needlessly bloating the GUI with things like this.

```
@echo off
taskkill /im monerod.exe
del %PROGRAMDATA%/bitmonero/p2pstate.bin
```
Honestly, deleting the p2pstate.bin is a kludge. We'd be better off solving the root cause.

**Comment by xmrdsc** [comment] 2018-12-12 11:32
This issue has not received any attention for over a year. I'd argue we can keep this functionality out of the GUI. @QuickBASIC Feel free to submit your shell script as a PR. Closing for now.

+resolved

**Closed** 2018-12-15 08:36 UTC
Labels: resolved
