### ISSUE TITLE
Sent Monero GUI, but wasn't received? Any ideas? Thank you

### ISSUE THREAD

**Issue by nocodemike** [monero-project/monero-gui#3416] opened 2021-04-19 12:48 UTC
Transaction ID: 993b3481eda12439b17b66c707b5314be39d1c3f5ca5dd00bacd1b8cfaaf62fe

**Comment by selsta** [comment] 2021-04-19 13:49
Please post a bit more Information.

Which OS?
Which version?
Did you use Monero GUI to send or receive the funds?
Are you using a hardware wallet?

**Comment by nocodemike** [comment] 2021-04-19 14:27
> Please post a bit more Information.
> 
> Which OS?
> Which version?
> Did you use Monero GUI to send or receive the funds?
> Are you using a hardware wallet?

Mac OS Big Sur (11.2.3)
Sent Monero via GUI Local Node
450 confirmations so far...

Not using a hardware wallet right now.

**Comment by selsta** [comment] 2021-04-19 14:28
Who is the one receiving the monero? Also you?

**Comment by nocodemike** [comment] 2021-04-19 14:36
> Who is the one receiving the monero? Also you?

No, I sent it to someone else - I've confirmed they haven't received it either.

**Comment by selsta** [comment] 2021-04-19 14:40
The issue is on the receiver side. Which wallet does the receiver use?

**Comment by selsta** [comment] 2021-05-08 15:03
Closing. If the receiver continues to have issues please reach out to Reddit r/monerosupport

**Closed by selsta** 2021-05-08 15:03 UTC
