### ISSUE TITLE
Flathub verification

### ISSUE THREAD

**Issue by Roman19S** [monero-project/monero-gui#4302] opened 2024-04-05 02:55 UTC
Can you verify the flatpak so people who find it through Flathub know it's safe? Here's a link to Flathub's verification documentation for developers https://docs.flathub.org/docs/for-app-authors/verification/

**Comment by TNTBOMBOM** [comment] 2024-05-23 12:12
duplicate of #4206

**Closed** 2024-05-23 13:49 UTC
