### ISSUE TITLE
XMR balance remaining zero and not showing recent deposit on GUI wallet

### ISSUE THREAD

**Issue by RSKmain** [monero-project/monero-gui#3662] opened 2021-08-09 16:01 UTC
Hi,
I’ve recently withdrawn a small amount of XMR from an exchange to my monero gui wallet (linked with Ledger) but unfortunately the balance remains zero and not acknowledging the withdrawal recently completed.
I am running a local node (prune blockchain), advanced fully synced wallet mode. I tried restoring wallet height to a day prior to my withdrawal (2401108) but the balance remains zero.
Could you help?

**Comment by rating89us** [comment] 2021-08-09 16:36
Does the transaction appear on a block explorer? You can verify this by entering your transaction ID (txid) in a block explorer (like https://www.exploremonero.com/).

**Comment by rating89us** [comment] 2021-08-09 16:39
What number do you see here?
![image](https://user-images.githubusercontent.com/45968869/128741806-82a4e0cd-6235-4876-bddf-66455b3c481d.png)

And what number do you see here (Settings > Info page)?
![image](https://user-images.githubusercontent.com/45968869/128741967-5a44d289-5c3a-4ab4-9128-9bd3dfbd2df0.png)

**Comment by RSKmain** [comment] 2021-08-11 18:20
Hi there,

Thank you so muchfor your reply.

I did try to to verify the transaction as you suggested but noted that the secret key is a list of zeros.

I also noted that the daemon is fully synchronised (Synced 2424923) but the wallet is not and seems to be stuck (not even starting).

I tried to change the wallet restore height (2401108) to a day prior to my initial test transaction from the exchange but the balance remains at 0.

I am running a local node on win10 x64and my wallet is on advanced mode and linked with Ledger Nano S.

Would you be able to advise me further?

Thank you for your time and help.

Regards,
R

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rating89us** [comment] 2021-08-13 12:47
> Hi there, Thank you so much for your reply. I did try to to verify the transaction as you suggested but noted that the secret key is a list of zeros.

You did it wrong. Please folow these steps:

1) Go to your exchange website, and search for history of transactions, withdrawal history or something similar.

2) Copy the transaction id (also known as txid, tx hash, or transaction hash) of your withdrawal transaction.

3) Paste the transaction ID in the search bar of exploremonero.com and press Enter:
![image](https://user-images.githubusercontent.com/45968869/129358554-20b5d162-d1ed-4974-ad25-85b972be7f83.png)

If you see a page with all transaction details (like the one below), the transaction was sent and the problem is that your wallet is not detecting it. Please inform us what number is displayed on "Block" (red circle below):
![image](https://user-images.githubusercontent.com/45968869/129359219-f7bfd077-8863-464b-b3a9-4efe03883602.png)

If you see a page with no transaction details, the problem was on your exchange and you should contact their support:
![image](https://user-images.githubusercontent.com/45968869/129358685-d8b0af67-b167-4465-addd-f3e2391eb297.png)

**Comment by RSKmain** [comment] 2021-08-13 18:51
Hi Rating89us,

Many thanks for getting back to me.
You were right - I was not using exploremonero correctly.
Using the transaction ID in the search bar, it gave the following block number: [2,422,574](https://www.exploremonero.com/block/2422574).

Hope this can help resolving the issue with the wallet.

Thank you,
R

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rating89us** [comment] 2021-08-14 03:13
Ok, so the issue seems to be on your wallet.

Did you allow Ledger to export the private view key to you computer when asked?

On the lower left corner, are both orange bars (daemon and wallet) synchronized?

**Comment by RSKmain** [comment] 2021-08-14 11:43
Hi,

Everytime I open the wallet, I decline for the keys to be exported to the computer - The link with instructions that I used to connect the GUI wallet with Ledger suggested not to allow the keys to be exported.

Only the daemon is fully synchronised. The wallet synchronisation bar remains empty/no orange colour at all.

Thank you and hope to hear from you soon.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rating89us** [comment] 2021-08-14 13:16
> Everytime I open the wallet, I decline for the keys to be exported to the computer 

This is your problem. You should always allow your Ledger to export the private view key to your computer, otherwise it will not work (in some cases it will work, but really slow).

It's safe to export the private view key to your computer, since it only allows Monero GUI to see the incoming transactions. You are not exporting the seed or the private spend key, therefore your computer won't be able to spend the funds without a connected Ledger.

Read this paragraph in Monero GUI guide which comes with Monero GUI:
![image](https://user-images.githubusercontent.com/45968869/129447344-5dbbda1a-9da0-4cc5-b483-fc04736a699b.png)

We will contact Ledger so they can update the instructions on their website. Some users are reporting that they are afraid of allowing the exporting of the private view key because they've read those instructions on Ledger website.

**Comment by selsta** [comment] 2021-08-15 02:37
Closing at is seems a user error (declining view key). I will reopen if the issue continues to persist.

**Closed by selsta** 2021-08-15 02:37 UTC

**Comment by RSKmain** [comment] 2021-08-15 07:37
Thank you for the support!
Wallet is now synced, balance is now correct and wallet is working perfectly!

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
