### ISSUE TITLE
Send page: impossible to paste into the amount inputbox

### ISSUE THREAD

**Issue by l29ah** [monero-project/monero-gui#3661] opened 2021-08-07 20:39 UTC
Both with right-click->paste and ctrl-v. Pasting in the address box works. Version 0.17.2.0 on Gentoo GNU/Linux here.

**Comment by selsta** [comment] 2021-08-08 00:37
Can't reproduce. Can you post the number you have attempted to paste?

**Comment by l29ah** [comment] 2021-08-08 00:43
10.6049880561322
Oh, apparently it checks the data before allowing it to be pasted and silently discards it when it doesn't like it. That's a shame.

**Comment by selsta** [comment] 2021-08-08 02:31
Yes, that's not a valid amount.

**Comment by selsta** [comment] 2021-08-08 02:32
Closing as pasting into the amount box works as long as the amount is valid.

**Closed by selsta** 2021-08-08 02:32 UTC

**Comment by l29ah** [comment] 2021-08-08 10:03
Certainly a valid amount, reopen plz.

**Comment by l29ah** [comment] 2021-08-08 10:05
Is user supposed to remember, count and trim how much digits after the dot is meaningful in Monero?

**Comment by selsta** [comment] 2021-08-08 11:54
Monero supports 12 decimal digits. Your example number has 13. Silently dropping digits after pasting would be worse than not pasting it at all.

The only thing that can improved would be an error message.

**Comment by chaserene** [comment] 2021-09-16 21:45
> Silently dropping digits after pasting would be worse than not pasting it at all.

@selsta why? this argument would be valid if it mattered financially, e.g. 10s of dollars of difference after trimming, but XMR is safely far from that. I agree with @l29ah, the amount should be trimmed, you can't expect novice users (=a goal demographic of the GUI wallet) to realize why pasting doesn't work, or remember how many decimals the protocol supports. especially since defining the amount in fiat is not yet possible, so you can pretty much expect they will try to paste a value from a calculator app, and those divisions tend to yield a lot of decimals.
