### ISSUE TITLE
Pending stuck

### ISSUE THREAD

**Issue by Simao12W** [monero-project/monero-gui#3140] opened 2020-10-08 11:45 UTC
So i made everything from this topic https://monero.stackexchange.com/questions/6649/transaction-stuck-as-pending-in-the-gui
I send for the 2nd time and I still have a transaction pending, 18 minutes 0/10 confirmations. A transfer to me was in 2 minutes. 
I tried to sent 3 transactions, 1 was ok. 

>>> relay_tx e315d781a29f04a4589de35d2570f4c8029cfdc0b08423ebf8202b8d8cf47b31
[08.10.2020 13:53] 2020-10-08 11:53:57.193 I Monero 'Oxygen Orion' (v0.17.0.1-release) 
Error: Unsuccessful -- json_rpc_request:

**Comment by xiphon** [comment] 2020-10-08 13:14
What wallet mode are you using? What steps did you do and what results did you get?

**Comment by Simao12W** [comment] 2020-10-08 15:12
Simply mode, flushed tx, renamed wallet name to old, restarted and then sent for the 2nd time. 
Now I did once more and i have clean history. What to do know?

**Comment by xiphon** [comment] 2020-10-08 17:05
Did you try switching to another remote node (the "shuffle" icon near the connection status bars)?

**Comment by Sorb78** [comment] 2020-10-09 23:09
Me and four other users have the same problem here:

https://www.reddit.com/r/Monero/comments/j871b8/transaction_not_being_confirmed/
https://www.reddit.com/r/Monero/comments/j86o7l/stuck_in_waiting_for_confirmation/
https://www.reddit.com/r/Monero/comments/j7umwx/tx_not_getting_confirmed_what_to_do/
https://www.reddit.com/r/monerosupport/comments/j7lnfa/help_me_please_monero_confirmation_010/

Either this version of monero-gui or the Ledger app is borked.

**Comment by selsta** [comment] 2020-10-09 23:12
@Sorb78 Are you also using simple mode?

We will release v0.17.0.2 soon and revert a change we did with the last release.

**Comment by selsta** [comment] 2020-10-09 23:13
In the meantime you can select Advanced mode and manually connect to a remote node, this should resolve the sending issue for now.

**Comment by Sorb78** [comment] 2020-10-09 23:16
Yes I am using simple mode as I only have 18 GB available on my SSD.
Ok hope the new release will fix it. Thanks!

**Comment by selsta** [comment] 2020-10-09 23:17
@Sorb78 You can go to the main menu by clicking on the exit symbol in the top left corner.

Then click on "Change wallet mode" and select "Advanced mode". Afterwards open your wallet again, go to Settings -> Node, select "Remote node" and enter the following node:

address: `node.xmr.to`
port: `18081`

This should resolve your issue for now.

**Comment by Sorb78** [comment] 2020-10-09 23:28
Thanks for the instructions. I tried it but it did not help. I tried to send the stuck transaction with relay_tx but I got the same error again as in the first post from Simao12W above. I then created a new transaction and it said "Transaction successfully sent!" but once again it was not sent to the mempool.

I can try the new version when it's released and delete the wallet file again.

**Comment by selsta** [comment] 2020-10-09 23:32
Please try again with new wallet file. The workaround I posted should definitely work with a fresh wallet, as it does not use the code we changed at all. Sending a transaction might take up to 5 seconds to 3 minutes to show up in the mempool, depending on how successful Dandelion++ is.

**Comment by Sorb78** [comment] 2020-10-09 23:34
Wait, something's happening! 😄 I refreshed xmrchain.net and now it's there with two confirmations!! 🎉

**Comment by dccasciato** [comment] 2020-10-10 03:38
@selsta : Is there a way to generate a new wallet file to use your workaround:

_Then click on "Change wallet mode" and select "Advanced mode". Afterwards open your wallet again, go to Settings -> Node, select "Remote node" and enter the following node:

address: node.xmr.to
port: 18081_

but **also** transfer funds from the old wallet file to be used there? I ask because using the remote node with the existing wallet does indicate that everything is connected and synchronized... tho the status command gives me this 

Error: Couldn't connect to daemon: 127.0.0.1:18081

Is this because I am using the existing wallet file? If so, my funds are held up and are not transferable to the new wallet file when I generate it...

**Comment by selsta** [comment] 2020-10-10 03:44
Did you try if transfering worked with the workaround? If not, please try to create a new wallet file by restore from seed. Then try again.

> Error: Couldn't connect to daemon: 127.0.0.1:18081

You can ignore this as long as it says synchronized in the bottom left corner.

**Comment by dccasciato** [comment] 2020-10-10 03:56
ok, all good now. thanks for the quick response!

**Comment by molecular** [comment] 2020-10-10 20:26
thanks for all the infos, guys. I was getting frustrated...

**Comment by selsta** [comment] 2020-10-13 20:24
v0.17.1.0 has been tagged and will be released tomorrow.

**Comment by selsta** [comment] 2020-10-14 14:14
https://www.getmonero.org/2020/10/14/monero-GUI-0.17.1.0-released.html

**Closed by selsta** 2020-10-14 14:14 UTC
Labels: bug

**Comment by molecular** [comment] 2020-10-15 14:21
confirming it 0.17.1.0 fixes the issue for me

**Comment by userlip** [comment] 2020-10-18 08:38
Just wanted to say that I currently am experiencing this bug with the newest version (0.17.1.0).
I don't know much about troubleshooting but just let me know how I can be of help (should I open a new Issue?)

**Comment by alan-camilo** [comment] 2020-11-03 23:30
I am running 0.17.1.1 GUI on Debian and I am facing the exact same issue when trying to send xmr with a local node. The workaround given by @selsta using a remote node works but even with the last version the issue  is **not** solved when using the simple mode.

**Comment by xiphon** [comment] 2020-11-04 00:29
We are actively working on it. There will be new release in a few days.

**Comment by peterbelau1** [comment] 2020-12-03 21:18
FYI, I'm still seeing this issue as of v0.17.1.5-release

**Comment by selsta** [comment] 2020-12-03 21:50
@peterbelau1 Simple mode? Are you sure that it really is failing or do they still confirm after a couple minutes even if they initially display failed?

**Comment by peterbelau1** [comment] 2020-12-04 19:26
My apologies -- this seems to be the wrong bug thread although related to the same issue(?) What I'm experiencing seems to be documented here:

https://www.reddit.com/r/Monero/comments/k5vvsf/update_01715_slow_current_blocks/
