### ISSUE TITLE
Unable to switch wallet modes

### ISSUE THREAD

**Issue by Electricsheep01** [monero-project/monero-gui#2018] opened 2019-03-15 01:52 UTC
When setting up a wallet in simple mode I am unable to then switch to other wallet modes. This should be an option so if people decide they do want to run a full node they can.

**Comment by Electricsheep01** [comment] 2019-03-15 01:54
To add to this, when closing my wallet it seems I am unable to change wallet mode at all once I have selected one.

**Comment by selsta** [comment] 2019-03-15 02:03
Thanks for reporting! I think this is a duplicate of #1957 though.

**Comment by xmrdsc** [comment] 2019-03-15 02:24
+duplicate

**Closed** 2019-03-15 02:27 UTC
Labels: duplicate
