### ISSUE TITLE
XMR transaction completed but not received

### ISSUE THREAD

**Issue by Rizla3** [monero-project/monero-gui#4018] opened 2022-08-29 09:29 UTC
Hi everyone, 

I am having an issue with my GUI wallet - I sent XMR from a crypto exchange and the funds have not been credited to my GUI wallet although the transaction is completed (confirmed by exploremonero). 

I re-synched my GUI wallet several times and changed the wallet restore height but that didn't help. My current GUI version is the 0.17.3.1

Any help or tips would be much appreciated ! Thanks :)

**Comment by selsta** [comment] 2022-08-30 00:37
monero had a network upgrade on August 13th. You have to use v0.18.0.0 or newer to send and receive coins. There should also be an update notification when using monero-gui, is it possible that you skipped that?

**Comment by selsta** [comment] 2022-08-30 22:20
Closing this as the issue is simply outdated software. Please comment if you continue to have issues after updating.

**Closed by selsta** 2022-08-30 22:20 UTC
