### ISSUE TITLE
GUI glitch after scrolling in Settings

### ISSUE THREAD

**Issue by rex4539** [monero-project/monero-gui#1255] opened 2018-04-04 10:03 UTC
GUI version: v0.12.0.0
macOS 10.13.4 (17E199)

Reproducibility: always

Steps:

1. In Settings, scroll down and leave scroller in some random position.
2. Switch to another tab.

What happened:
Content is not drawn.

https://www.dropbox.com/s/2v1dbqwtma3660q/Monero%20GUI%20glitch%202.mp4?dl=0

Expected result:
No glitch.

**Comment by skftn** [comment] 2018-04-04 12:07
duplicate of #1160

**Comment by skftn** [comment] 2018-04-04 12:07
+duplicate

**Closed** 2018-04-04 12:09 UTC
Labels: duplicate
