### ISSUE TITLE
file chooser dialog doesn't show hidden files/folders on Linux

### ISSUE THREAD

**Issue by salim-b** [monero-project/monero-gui#1495] opened 2018-07-05 13:04 UTC
I've just upgraded to GUI 0.12.2.0 and tried to open my wallet file which resides in the folder `~/.monero_wallets`. It seems impossible to navigate to that folder because I can't find a way to make the file chooser dialog show hidden folders. This seems like a major usability flaw to me....

For now possible workarounds include:
- Set the variable `wallet_path` in `~/.config/monero-project/monero-gui.conf` by hand to the correct (hidden) path
- or move the wallet file(s) to a non-hidden folder.

I'm using Ubuntu 16.04 LTS.

**Comment by pazos** [comment] 2018-07-08 16:59
Don't remember if being a qml app changes this, but:
on file chooser -> right click -> show hidden folders - doesn't work?

**Comment by skftn** [comment] 2018-07-10 08:15
Doubt this is due to Qt. Try the shortcut `CTRL-H`.

**Comment by pazos** [comment] 2018-08-19 22:33
I can confirm than right click on the file chooser will display an option to show/hide hidden files. @salim-b, please test

**Comment by dEBRUYNE-1** [comment] 2018-12-17 08:14
The author has not responded to the suggestions. I therefore am going to close this issue.

**Comment by dEBRUYNE-1** [comment] 2018-12-17 08:14
+resolved

**Closed** 2018-12-17 09:09 UTC
Labels: resolved
