### ISSUE TITLE
Gui crashing on start - Failed to determine whether address '' is local, assuming not

### ISSUE THREAD

**Issue by pedro-reis** [monero-project/monero-gui#1302] opened 2018-04-09 09:18 UTC
Windows 10 64Bits with 64Bits Wallet v0.12

2018-04-09 09:15:22.631	9812	INFO 	logging	contrib/epee/src/mlog.cpp:185	New log categories: *:WARNING,net:FATAL,net.p2p:FATAL,net.cn:FATAL,global:INFO,verify:FATAL,stacktrace:INFO,logging:INFO,msgwriter:INFO
2018-04-09 09:15:23.892	9812	WARN 	net.http	src/common/util.cpp:627	Failed to determine whether address '' is local, assuming not

**Comment by stoffu** [comment] 2018-04-09 09:35
That warning message is normal and can be ignored. Perhaps the issue is due to the graphics card. Please refer to https://monero.stackexchange.com/questions/7997/windows-gui-v0-12-does-not-launch-start and try running the GUI with `start-low-graphics-mode.bat`.

**Comment by dEBRUYNE-1** [comment] 2018-07-04 08:38
This particular issue is resolved in GUI v0.12.2.0: 

https://www.reddit.com/r/Monero/comments/8vkx2g/gui_v01220_released/

**Comment by dEBRUYNE-1** [comment] 2018-07-04 08:38
+resolved

**Closed** 2018-07-04 10:00 UTC
Labels: resolved
