### ISSUE TITLE
0.13.0.3 GUI  macOS 10.14 not working

### ISSUE THREAD

**Issue by geli-ans** [monero-project/monero-gui#1675] opened 2018-10-17 06:23 UTC
macOS 10.14 can't open  0.13.0.3 GUI。
old version works well。

**Comment by dEBRUYNE-1** [comment] 2018-10-17 07:11
Duplicate of #1658. A quick resolution can be found here:

https://monero.stackexchange.com/questions/10364/gui-v0-13-0-3-does-not-start-on-mac-os-x-monero-wallet-gui-cannot-be-opened-bec

**Comment by dEBRUYNE-1** [comment] 2018-10-17 07:11
+duplicate

**Closed** 2018-10-17 07:18 UTC
Labels: duplicate
