### ISSUE TITLE
Transaction shows %n seconds ago

### ISSUE THREAD

**Issue by asheroto** [monero-project/monero-gui#3652] opened 2021-07-31 23:43 UTC
Windows x64
Monero GUI version 0.17.2.2

Transactions are correct for hours/days but seconds shows `%n`.

![image](https://user-images.githubusercontent.com/49938263/127754824-0975fffe-9975-499f-bbdf-ecaf469703a2.png)

Pixelated other info for privacy.

**Comment by selsta** [comment] 2021-07-31 23:54
Thanks for reporting.

Closing as duplicate of #3284

**Closed by selsta** 2021-07-31 23:54 UTC
