### ISSUE TITLE
Link to MacOS ARM goes to intel version for the v0.18.3.1 release

### ISSUE THREAD

**Issue by Noiden** [monero-project/monero-gui#4226] opened 2023-10-11 18:54 UTC
The link to the MacOS ARM version in the latest release goes to the Intel x64 build.
https://github.com/monero-project/monero-gui/releases

Where can I find the ARM version?

The download link for the ARM version is also broken on https://downloads.getmonero.org/gui/macarm8
I get 404 Not Found error there.

Thanks.

**Comment by plowsof** [comment] 2023-10-11 21:16
Thank you for reporting this. Do not worry, the problem is known and will be fixed shortly https://libera.monerologs.net/monero-site/20231011

**Comment by selsta** [comment] 2023-10-12 10:10
Issue should be resolved now.

**Closed by selsta** 2023-10-12 10:10 UTC
