### ISSUE TITLE
problem with receiving XMR on GUI wallet

### ISSUE THREAD

**Issue by TTwallet** [monero-project/monero-gui#4074] opened 2022-11-29 08:57 UTC
Hi there, 
3 weeks ago I withdraw some XMR from Binance to GUI wallet.  And it never received, I thought maybe it had to do something with the update that is required on Ledger live app but I did the update yesterday and I logged into my GUI wallet and still not received my XMR. I contacted Binance support service and from their end everything is correct, transaction was completed. Can someone maybe help me with this matter? I have the tixd link and transaction information. thanks in advance.

**Comment by selsta** [comment] 2022-11-29 10:12
Please go to Settings -> Info and post

- Version
- Wallet restore height
- Wallet mode

**Comment by selsta** [comment] 2022-11-29 12:06
Post them here and I will tell you if they are ok, the other way around makes everything more complicated.

**Comment by TTwallet** [comment] 2022-11-29 12:36
thanks alot I will check it when I am home.

**Comment by gickyDEV** [comment] 2022-11-30 07:28
Talk to ledger Support on the [live chat](https://explore-ledger.org/) so that your issue can be looked into

**Comment by selsta** [comment] 2022-11-30 11:06
Ignore the message above, seems now there are also live chat scammers on GitHub.

**Comment by TTwallet** [comment] 2022-11-30 20:23
Hi there, 

I looked it up, here are is the info:

version: 0.18.1.2-unknown (Qt 5.15.6)
wallet height: 2581447
mode:  Advanced mode (Local node)

**Comment by plowsof** [comment] 2022-11-30 21:55
you're using the latest version. perhaps the problem is with your local node. have you tried re-syncing from a remote node e.g. selsta2.featherwallet.net:18081?
- Settings 
- Node -> click Remote node
- (+) Add remote node
- Address = selsta2.featherwallet.net
- Port = 18081
- OK. now make sure the node is clicked / highlighted grey in the list under 'Add remote node' 
- it should say connected eventually
- To resync your wallet go to Settings -> Info -> click change next to restore height -> dont change anything , just click ok -> ok

**Comment by TTwallet** [comment] 2022-12-01 08:47
Did not changed my node yet, I changed the height of the wallet to the height of the frist receiving transaction. after I did that, it showed only less balance.. Do you think that changing the node will be the solution? thank you for your help so far.

**Comment by selsta** [comment] 2022-12-01 11:21
@TTwallet please go to Settings -> Log, enter "status" into the textbox and post the output here. Then we can see if your node is properly synced.

**Comment by TTwallet** [comment] 2022-12-03 20:02
[3-12-2022 20:17] 2022-12-03 19:17:52.209 I Monero 'Fluorine Fermi' (v0.18.1.2-release) 
Height: 1481118, target: 2769435 (53.4809%) 
Downloading at 31 kB/s 
Next needed pruning seed: 3 
4 peers 
Remote Host Peer_ID State Prune_Seed Height DL kB/s, Queued Blocks / MB 
92.205.62.235:18080 f88d8eb9646e0206 synchronizing 0 2769435 11 kB/s, 0 blocks / 0 MB queued 
141.98.11.121:18080 dc4dc31afcc3eb97 synchronizing 181 2769435 8 kB/s, 0 blocks / 0 MB queued 
136.33.130.147:18080 8e02306afbe91337 synchronizing 0 2769435 11 kB/s, 0 blocks / 0 MB queued 
47.157.248.110:18080 2f208bbf8bc7c4bb normal 0 1 1 kB/s, 0 blocks / 0 MB queued 
0 spans, 0 MB 
[]

**Comment by TTwallet** [comment] 2022-12-03 20:04
I changed the block height again, but it is still not showing the last transaction.

**Comment by TTwallet** [comment] 2022-12-03 20:05
sorry for the late reply, it was a verry busy week for me

**Comment by selsta** [comment] 2022-12-03 20:26
Your node is only 53% synced. You either have to wait for it to fully sync up to 100%, or use a remote node.

**Comment by selsta** [comment] 2023-01-18 05:59
Closing as this is a support ticket and there's no update from issue creator.

**Closed by selsta** 2023-01-18 05:59 UTC
