### ISSUE TITLE
NanoX device not working for sending transfers.  In only

### ISSUE THREAD

**Issue by taylormade2k** [monero-project/monero-gui#2577] opened 2019-12-08 23:46 UTC
When I tray and send monero from my NanoX I get this spinning wheel that says "Creating transaction please check your hardware wallet your input may be required" This has been going for 15 minutes now. The nano does not appear to see the transaction request to take action.  

Troubleshooting.  Checked to make sure my nano x was updated to the latest version which is 1.2.4-1
Uninstalled all apps on nano and reinstalled BTC first then monero.

**Comment by xiphon** [comment] 2019-12-09 10:54
What Monero app version is installed on the device?

**Comment by taylormade2k** [comment] 2019-12-09 16:23
Hi, Its v0.15.0.1 (Qt 5.9.7)

**Comment by xiphon** [comment] 2019-12-09 19:55
I mean the Ledeger Monero app version, the one you have installed on the device.

**Comment by taylormade2k** [comment] 2019-12-09 20:27
Ah Ok, Its App 1.4.2 Spec 1.0

**Comment by xiphon** [comment] 2019-12-09 23:44
Reproduced the issue once. But when i enabled the debug logs and i can't reproduce it again.

Could you please try to send the tx once again and wait for some minutes (5 mins should be okay) and report back?

**Comment by taylormade2k** [comment] 2019-12-10 01:01
Sure I will do that shortly.

**Comment by xiphon** [comment] 2019-12-10 01:06
Try without the logs first, if the issue reproduces give it another run with log level 4.

**Comment by taylormade2k** [comment] 2019-12-10 02:13
Ok it worked after rrunning log level 4.  Before that same thing happened.  The infinite spin loop saying check your nano for further instructions.  I was able to transfer a test balance out.  It seemed a bit clunky asking me for my password multiple times but it worked, and I'm thankful for that.

**Comment by selsta** [comment] 2019-12-10 02:25
ping @cslashm

**Comment by cslashm** [comment] 2019-12-10 08:44
I never see that and I am not able to reproduce :-/

**Comment by selsta** [comment] 2021-06-29 03:05
Closing as a lot has changed since this issue was opened, including Ledger firmware updates.

**Closed by selsta** 2021-06-29 03:05 UTC
