### ISSUE TITLE
Cannot use Ledger-based wallet: "Invalid Password"

### ISSUE THREAD

**Issue by Apy17750** [monero-project/monero-gui#3088] opened 2020-09-14 18:46 UTC
I am attempting to create a new wallet from a hardware Ledger device (Nano X) using the Monero GUI (v0.16.0.3 - Nitrogen Nebula, though I also encounted this issue on 0.16.0.2) on macOS (v10.15.6). I followed the steps [here](https://monero.stackexchange.com/questions/9901/how-do-i-generate-a-ledger-monero-wallet-with-the-gui-monero-wallet-gui).

I can successfully create the wallet and set any password; however, I consistently receive the following error while attempting to open the wallet:

<img width="462" alt="image" src="https://user-images.githubusercontent.com/71286826/93124624-bcad2f00-f67e-11ea-97dc-0fa07169f257.png">

I've tried setting & opening with:
* No password
* The letter 'a'
* A random password, copied & pasted both times

I've tried both the restore & the create new wallet options, and both have this issue. I found a [Reddit thread](https://www.reddit.com/r/monerosupport/comments/hxqv2m/monero_gui_and_ledger_invalid_password/) where a Windows user is describing a similar issue.

Steps to reproduce:
1. Open a new Monero wallet on the Ledger device
2. Attempt to create or restore a wallet from a hardware device in the Monero GUI
3. Set any passphrase
4. Attempt to open the wallet (which happens automatically)

**Comment by selsta** [comment] 2020-09-16 01:27
Does this only happen when creating a Ledger wallet?

**Comment by cryptonaus** [comment] 2020-09-16 16:52
I haven't tested with Trezor devices, but choosing the "Create a new wallet" option works without issues.

**Comment by selsta** [comment] 2020-09-21 01:07
> Steps to reproduce:

Sadly I’m not able to reproduce. Anything else that you would call special with your setup?

**Comment by cryptonaus** [comment] 2020-09-25 21:24
The only other thing that I've done specially was select the advanced bootstrap mode. Otherwise, it was a fresh install of Monero GUI & Monero on the device itself. Perhaps the latter has been updated since then; I'll try again.

**Comment by gitfreebeer** [comment] 2021-02-19 05:51
I'm having the same issue on Linux. This is a new device, fresh install of everything, and the only custom parameter is I'm using a "remote" node running locally in another process, so the daemon isn't dependent on the GUI application.

Ubuntu 20.04.2
Ledger Nano X FW 1.2.4-5
monero-gui v0.17.1.9

Here's some syslog output:
FFeb 18 21:46:03 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:03.018#011I [PARSE URI] regex not matched for uri: ^((.*?)://)?(\[(.*)\](:(\d+))?)(.*)?
Feb 18 21:46:41 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:41.285#011W SSL peer has not been verified
Feb 18 21:46:41 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:41.482#011I ~WalletImpl
Feb 18 21:46:41 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:41.482#011I closing wallet...
Feb 18 21:46:41 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:41.482#011I Calling wallet::stop...
Feb 18 21:46:41 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:41.482#011I wallet::stop done
Feb 18 21:46:41 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:41.483#011I Generating SSL certificate
Feb 18 21:46:41 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:41.484#011I ~WalletImpl finished
Feb 18 21:46:41 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:41.487#011I ringdb path set to /home/dude/.shared-ringdb
Feb 18 21:46:48 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:48.728#011E portable_storage: wrong binary format - signature mismatch
Feb 18 21:46:48 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:48.729#011E !r. THROW EXCEPTION: error::invalid_password
Feb 18 21:46:48 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:48.730#011W /monero-gui/monero/src/wallet/wallet2.cpp:4353:N5tools5error16invalid_passwordE: invalid password
Feb 18 21:46:48 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:48.731#011E Error opening wallet: invalid password
Feb 18 21:46:48 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:48.744#011E Error opening wallet with password:  invalid password


That's all the detail I can find about the issue. If there's another log, or a way to launch the application with more extensive logs, I'll be happy to share those as well.

**Comment by gitfreebeer** [comment] 2021-02-19 05:53
I'm having the same issue on Linux. This is a new device, fresh install of everything, and the only custom parameter is I'm using a "remote" node running locally in another process, so the daemon isn't dependent on the GUI application.

Ubuntu 20.04.2
Ledger Nano X FW 1.2.4-5
monero-gui v0.17.1.9

Here's some syslog output:
FFeb 18 21:46:03 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:03.018#011I [PARSE URI] regex not matched for uri: ^((.?)://)?([(.)](:(\d+))?)(.*)?
Feb 18 21:46:41 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:41.285#011W SSL peer has not been verified
Feb 18 21:46:41 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:41.482#011I ~WalletImpl
Feb 18 21:46:41 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:41.482#011I closing wallet...
Feb 18 21:46:41 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:41.482#011I Calling wallet::stop...
Feb 18 21:46:41 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:41.482#011I wallet::stop done
Feb 18 21:46:41 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:41.483#011I Generating SSL certificate
Feb 18 21:46:41 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:41.484#011I ~WalletImpl finished
Feb 18 21:46:41 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:41.487#011I ringdb path set to /home/x/.shared-ringdb
Feb 18 21:46:48 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:48.728#011E portable_storage: wrong binary format - signature mismatch
Feb 18 21:46:48 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:48.729#011E !r. THROW EXCEPTION: error::invalid_password
Feb 18 21:46:48 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:48.730#011W /monero-gui/monero/src/wallet/wallet2.cpp:4353:N5tools5error16invalid_passwordE: invalid password
Feb 18 21:46:48 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:48.731#011E Error opening wallet: invalid password
Feb 18 21:46:48 x org.gnome.Nautilus[21216]: 2021-02-19 05:46:48.744#011E Error opening wallet with password: invalid password

That's all the detail I can find about the issue. If there's another log, or a way to launch the application with more extensive logs, I'll be happy to share those as well.

**Comment by selsta** [comment] 2021-02-19 23:03
@gitfreebeer Thanks for the logs, "Wrong binary format - signature mismatch" might be interesting.

**Comment by selsta** [comment] 2021-02-19 23:51
@gitfreebeer could you please also test if you can open the wallet fine with monero-wallet-cli?

**Comment by gitfreebeer** [comment] 2021-02-22 04:19
@selsta the CLI application worked. The GUI still does not. It doesn't even prompt for the key export before it fails.

...on this PC.

On another Linux box, with the same software, the GUI application opens this wallet fine. All the software, including the blockchain and the wallet file, were copied over from one to the other.

**Comment by moneromooo-monero** [comment] 2021-03-05 00:08
If you can run with this patch to monero-wallet-gui, can you:
- run with --log-level 2
- NOT paste the logs, as they'll contain your secret keys
- Look for a line starting with "Decrypted with chacha20", and one with "Decrypted with chacha8" (the latter might not be there)
- Check whether the data on the last of these lines look like JSON, similar to: {"key_data":"......
- Whether the log contains a line with "Keys file has wrong format"


```
diff --git a/src/wallet/wallet2.cpp b/src/wallet/wallet2.cpp
index d4727f957..0f6d2f45e 100644
--- a/src/wallet/wallet2.cpp
+++ b/src/wallet/wallet2.cpp
@@ -4214,11 +4214,16 @@ bool wallet2::load_keys_buf(const std::string& keys_buf, const epee::wipeable_st
   std::string account_data;
   account_data.resize(keys_file_data.account_data.size());
   crypto::chacha20(keys_file_data.account_data.data(), keys_file_data.account_data.size(), key, keys_file_data.iv, &account_data[0]);
+MGINFO("Decrypted with chacha20: " << account_data);
   if (json.Parse(account_data.c_str()).HasParseError() || !json.IsObject())
+  {
     crypto::chacha8(keys_file_data.account_data.data(), keys_file_data.account_data.size(), key, keys_file_data.iv, &account_data[0]);
+MGINFO("Decrypted with chacha8: " << account_data);
+  }
   // The contents should be JSON if the wallet follows the new format.
   if (json.Parse(account_data.c_str()).HasParseError())
   {
+    MERROR("Keys file has wrong format");
     is_old_file_format = true;
     m_watch_only = false;
     m_multisig = false;
@@ -4517,6 +4522,9 @@ bool wallet2::load_keys_buf(const std::string& keys_buf, const epee::wipeable_st
     return false;
   }
 
+MGINFO("account_data (len): " << account_data.size());
+MGINFO("account_data (hex): " << epee::string_tools::buff_to_hex_nodelimer(account_data));
+MGINFO("account_data (raw): " << account_data);
   r = epee::serialization::load_t_from_binary(m_account, account_data);
   THROW_WALLET_EXCEPTION_IF(!r, error::invalid_password);
   if (m_key_device_type == hw::device::device_type::LEDGER || m_key_device_type == hw::device::device_type::TREZOR) {
```

**Comment by gitfreebeer** [comment] 2021-03-25 00:54
@moneromooo-monero, I'm not sure what to do with that code. I've checked out tags/v0.17.1.9 on a local repo, but where do I apply the code. I assume I'm supposed to compile from source with that code pasted somewhere?

**Comment by selsta** [comment] 2021-03-25 14:25
@gitfreebeer  try

```
cd monero-gui/monero
patch -p1 < /path/to/patch
cd ..
mkdir build
cd build
cmake -D MANUAL_SUBMODULES=ON ..
make -j2
```

**Comment by fabiobfava** [comment] 2021-04-19 19:57
> > Steps to reproduce:
> 
> Sadly I’m not able to reproduce with Ledger on macOS. Anything else that you would call special with your setup?

I'm using Monero-GUI-Mac version 0.17.2.1 and this issue persists. The wallet can be created and password set, but Monero-GUI-Mac cannnot open the wallet, may it be created by itself or monero-wallet-cli, wich is actually not working very well, it freezes after connecting to the Ledger and never stops "Refreshing..."

**Comment by selsta** [comment] 2021-04-19 19:58
> it freezes after connecting to the Ledger and never stops "Refreshing..."

Did you export your view key?

**Comment by fabiobfava** [comment] 2021-04-19 20:00
Can't understand what you mean. It's a Ledger wallet.

**Comment by selsta** [comment] 2021-04-19 20:01
Did you accept exporting the view key on the Ledger device after opening your wallet?

**Comment by fabiobfava** [comment] 2021-04-19 20:01
No, but it works this way. Sometimes it freezes.

**Comment by selsta** [comment] 2021-04-19 20:02
> No, but it works this way. Sometimes it freezes.

You have to accept exporting the view key. The Ledger device is not strong enough to do all calculations on device so it will freeze.

**Comment by fabiobfava** [comment] 2021-04-19 20:05
Ok I'll try it now. No problem on reduced privacy?

**Comment by selsta** [comment] 2021-04-19 20:10
At worst someone could see your incoming transactions if they hacked your computer. But if your computer is hacked they can see your incoming transactions anyway once you open the wallet.

**Comment by fabiobfava** [comment] 2021-04-19 20:13
Nobody has hacked my pc. Thank you for the infos it's now working and very fast! Thanks!

On the other hand, Monero-GUI (Mac) cannot open the Ledger wallet. Any provisional date for having this fixed?

**Comment by selsta** [comment] 2021-04-19 20:15
> On the other hand, Monero-GUI (Mac) cannot open the Ledger wallet.

None of the devs were able to reproduce this yet. Until then not a lot we can do :/

**Comment by fabiobfava** [comment] 2021-04-19 20:32
Well, I have never managed to open my Ledger Monero wallet using Monero-GUI. The Application says the password is invalid. I've never found any solution to that, just using the monero-wallet-cli instead. But I'd rather prefer using the Monero-GUI. Not sure why this happens, the wallet and the keys just work.

**Comment by selsta** [comment] 2021-04-19 22:33
ping @gitfreebeer Do you maybe have time to compile moneromooo's diff? https://github.com/monero-project/monero-gui/issues/3088#issuecomment-806847524

It would be great help for us to potentially find this issue.

**Comment by fabiobfava** [comment] 2021-04-19 23:02
Thank you @selsta for looking a bit deeper into this. It's really impossible to open a wallet on my Ledger Nano X from the Monero-GUI-Mac. I can open it via Monero-GUI-Win64 and Monero-Wallet-CLI, but as a Mac-user since my childhood, I'd rather prefer to just open via Monero-GUI-Mac. Thanks folks!

**Comment by gitfreebeer** [comment] 2021-04-20 03:29
> @gitfreebeer try
> 
> ```
> cd monero-gui/monero
> patch -p1 < /path/to/patch
> cd ..
> mkdir build
> cd build
> cmake -D MANUAL_SUBMODULES=ON ..
> make -j2
> ```

I get an error that it can't find the file from line 5. It seems that it's looking for the wallet file? Is that correct?

~/Downloads/monero-gui/monero$ patch -p1 < ~/Downloads/monero-patch 
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/src/wallet/wallet2.cpp b/src/wallet/wallet2.cpp
|index d4727f957..0f6d2f45e 100644
|--- a/src/wallet/wallet2.cpp
|+++ b/src/wallet/wallet2.cpp
--------------------------
File to patch: ^C
~/Downloads/monero-gui/monero$

**Comment by selsta** [comment] 2021-04-20 04:23
@gitfreebeer Did you save

```
diff --git a/src/wallet/wallet2.cpp b/src/wallet/wallet2.cpp
index d4727f957..0f6d2f45e 100644
--- a/src/wallet/wallet2.cpp
+++ b/src/wallet/wallet2.cpp
@@ -4214,11 +4214,16 @@ bool wallet2::load_keys_buf(const std::string& keys_buf, const epee::wipeable_st
   std::string account_data;
   account_data.resize(keys_file_data.account_data.size());
   crypto::chacha20(keys_file_data.account_data.data(), keys_file_data.account_data.size(), key, keys_file_data.iv, &account_data[0]);
+MGINFO("Decrypted with chacha20: " << account_data);
   if (json.Parse(account_data.c_str()).HasParseError() || !json.IsObject())
+  {
     crypto::chacha8(keys_file_data.account_data.data(), keys_file_data.account_data.size(), key, keys_file_data.iv, &account_data[0]);
+MGINFO("Decrypted with chacha8: " << account_data);
+  }
   // The contents should be JSON if the wallet follows the new format.
   if (json.Parse(account_data.c_str()).HasParseError())
   {
+    MERROR("Keys file has wrong format");
     is_old_file_format = true;
     m_watch_only = false;
     m_multisig = false;
@@ -4517,6 +4522,9 @@ bool wallet2::load_keys_buf(const std::string& keys_buf, const epee::wipeable_st
     return false;
   }
 
+MGINFO("account_data (len): " << account_data.size());
+MGINFO("account_data (hex): " << epee::string_tools::buff_to_hex_nodelimer(account_data));
+MGINFO("account_data (raw): " << account_data);
   r = epee::serialization::load_t_from_binary(m_account, account_data);
   THROW_WALLET_EXCEPTION_IF(!r, error::invalid_password);
   if (m_key_device_type == hw::device::device_type::LEDGER || m_key_device_type == hw::device::device_type::TREZOR) {
```

as monero-patch? The patch command works here.

**Comment by selsta** [comment] 2021-04-20 07:44
@gitfreebeer You have to clone monero-gui first like this:

```
git clone --recursive https://github.com/monero-project/monero-gui
```

and then do the steps in my comment.

**Comment by fabiobfava** [comment] 2021-04-20 16:28
Hey @selsta I'm not sure what are KDF rounds. Sorry for my ignorance, thanks.

**Comment by fabiobfava** [comment] 2021-04-20 16:28
Yes they are

**Comment by fabiobfava** [comment] 2021-04-20 17:30
Yes @selsta it says 1 KDF round.

**Comment by selsta** [comment] 2021-04-20 18:54
@fabiobfava 

Can you select the `1` inside KDF rounds field, change it to `2` and then immediately after select and change it back to `1`? Afterwards please try to reopen the Ledger wallet.

**Comment by fabiobfava** [comment] 2021-04-20 19:37
Hey @selsta it works! I can now open my Ledger wallet on the Monero-GUI-Mac! Thank you so much!

**Comment by selsta** [comment] 2021-04-20 19:39
Thanks for confirming.

@gitfreebeer https://github.com/monero-project/monero-gui/issues/3088#issuecomment-823522464 should also resolve your issue.

**Comment by gitfreebeer** [comment] 2021-04-22 03:28
> Thanks for confirming.
> 
> @gitfreebeer [#3088 (comment)](https://github.com/monero-project/monero-gui/issues/3088#issuecomment-823522464) should also resolve your issue.

It does fix the issue for me.

**Closed** 2021-04-22 03:38 UTC
Labels: bug
