### ISSUE TITLE
Import and export outputs

### ISSUE THREAD

**Issue by jluttine** [monero-project/monero-gui#3388] opened 2021-04-11 16:48 UTC
Monero GUI "Send" tab gives the following instructions:

> Offline transaction signing:
>
> 1. Using view-only wallet, export the outputs into a file
> 2. Using cold wallet, import the outputs file and export the key images
> 3. ...
> 4. ...
> 5. ...

However, the GUI doesn't provide buttons to export and import the outputs. It would be nice to have such buttons available so that offline transaction signing could be done with the GUI wallet without needing to use the CLI wallet. Especially, as the GUI wallet gives the instructions, it seems weird that it cannot be done.

Or is this already possible but I just cannot find it?

**Comment by selsta** [comment] 2021-04-21 02:27
Closing as a duplicate of #2816.

Will try to add support for this in the next weeks.

**Closed by selsta** 2021-04-21 02:27 UTC
