### ISSUE TITLE
Extremely High Usage

### ISSUE THREAD

**Issue by cinjon** [monero-project/monero-gui#1349] opened 2018-04-23 01:02 UTC
I just downloaded the Monero GUI client for Mac and the usage is at 700% CPU, even after the wallet and daemon are synchronized. I'm right now using a remote node (node.moneroworld.com:18089). How can I reduce this?

**Comment by dEBRUYNE-1** [comment] 2018-04-23 11:26
It's, most likely, caused by the daemon (your local node) performing the initial sync. Could you perhaps post the output of `Show status`  (on the `Settings` page of the GUI)?

**Comment by cinjon** [comment] 2018-04-28 20:56
I don't see that option in the GUI.

**Comment by dEBRUYNE-1** [comment] 2018-04-29 10:16
It's button 10 -> https://github.com/monero-ecosystem/monero-GUI-guide/blob/master/media/black_settings.png. Or is your wallet mode set to `Remote node` (indicated by the button being grey)?

**Comment by ChurchOfNotNothing** [comment] 2018-05-24 03:46
I'm using the Monero GUI client for Mac as well and my CPU usage is also insane. Force programs to quit and I've never had that issue before. 
@dEBRUYNE-1 
I tried to click the 'Status' button you were referring to and there was no response. In fact, nothing responds except for the left hand [Send, Receive, Settings] but then when the screen changes nothing responds.

**Comment by dEBRUYNE-1** [comment] 2018-05-24 08:52
@ChurchOfNotNothing - Try applying this guide:

https://monero.stackexchange.com/questions/6651/my-gui-feels-buggy-freezes-all-the-time

**Comment by dEBRUYNE-1** [comment] 2018-07-04 08:44
This particular issue (the lag issue) is supposedly resolved in GUI v0.12.2.0: 

https://www.reddit.com/r/Monero/comments/8vkx2g/gui_v01220_released/

@cinjon and @ChurchOfNotNothing - Could you give it a try?

**Comment by xmrdsc** [comment] 2019-03-29 16:18
In addition, #1920 should help too. Closing this.

+resolved

**Closed** 2019-03-29 16:27 UTC
Labels: resolved
