### ISSUE TITLE
Lock wallet on inactivity time showing 14.7666666666666666666666 minutes

### ISSUE THREAD

**Issue by rating89us** [monero-project/monero-gui#2006] opened 2019-03-11 10:18 UTC
On macOS Mojave v.10.14.3, when you select a time to lock wallet, it first rapidly displays a long number (like 14.7666666666666666666666 minutes), which is rapidly rounded (to 15 minutes).
![image](https://user-images.githubusercontent.com/45968869/54382132-a55b4300-468f-11e9-924f-28d803fc51a0.png)

**Comment by xmrdsc** [comment] 2019-03-11 11:42
+bug

**Comment by mmbyday** [comment] 2019-03-13 02:01
Might be a Mac specific bug. Can't replicate on Windoze.

**Comment by selsta** [comment] 2019-03-14 18:11
Can’t reproduce on macOS.

**Comment by ProkhorZ** [comment] 2019-03-28 14:13
I get the same bug on Windows 10. It's also rounded down in the blink of an eye. Just managed to take a screenshot.

Maybe it's hardware-related and happens to fast to be visible on the shiny new gaming rigs used by devs?

![timer bug](https://user-images.githubusercontent.com/22837744/55164519-13156d80-516c-11e9-87ed-af3eadc52618.png)

**Comment by xmrdsc** [comment] 2019-03-28 21:59
Thanks @ProkhorZ 

I looked some more at our implementation:

https://github.com/monero-project/monero-gui/blob/d4d8ff54e6c94f82de7eb012d7b310addeedcbb9/pages/settings/SettingsLayout.qml#L155-L165

It is due to how earlier versions of Qt lack a `Slider.onMoved{}` event, thus, we can't reliably update the minutes whilst the user is changing the value.

This will be fixed when we switch to Qt 5.9.7 - possibly next release.

**Closed** 2019-04-25 20:26 UTC
Labels: bug
