### ISSUE TITLE
Transaction details reveal despite pressing decline on Trezor

### ISSUE THREAD

**Issue by maxbiddickk** [monero-project/monero-gui#3595] opened 2021-06-28 20:18 UTC
Transaction details reveal despite pressing decline on Trezor

**Comment by rating89us** [comment] 2021-06-28 20:51
It is expected behavior.

When you are on Transactions page and click on transaction details button, a export tx_key dialog will display on your Trezor. If you decline it, your trezor device will not export the tx key of this transaction to your computer.

The transaction details popup will always open and display the transaction details that are available to the wallet. If you decline exporting the tx key, only this information will not be displayed. The remaining transaction details are not imported from your hardware wallet device, and therefore are displayed.

**Comment by selsta** [comment] 2021-06-28 20:53
Closing as it seems working as intended.

@maxbiddickk please comment if you have more questions

**Closed by selsta** 2021-06-28 20:53 UTC

**Comment by maxbiddickk** [comment] 2021-06-29 11:05
Very cool ! My first post on GitHub. Happy to be involved even if some what unnecessarily 🤣 sorry to waste anybody’s time !

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
