### ISSUE TITLE
Reimbursement request for two transactions that never completed.

### ISSUE THREAD

**Issue by dustyheals** [monero-project/monero-gui#3339] opened 2021-02-20 06:40 UTC
1st Amount:
0.578778135048 XMR
2nd Amount:
0.56449926824 XMR

My Monero GUI Wallet Address for Reimbursement:
46DQdJLNSnsXEzsoJVzoYdeTym1RxdUCCYqt3ixw3YS1gLv7JcqsnQbLDVLQemBzztaPPe487NJCgYBftdqpnttxPJV8DZw

Full Details Below...

I don't know if I'm putting this request in the right place.  But I see other requests for reimbursements in other areas of GitHub and people are addressing them.  This is so far the best I can come up with, After exhaustive searching elsewhere, this is the only place that seems like it could be appropriate for me to place my request.

6 Days ago I sent two XMR transactions, each roughly $135 USD value, to an onion address through a trusted remote node that worked for me before.  I want to use a local node but it's taken forever to download the blockchain and it seems like the more that it downloads, the longer the remaining estimated time becomes.  It's a head-scratcher.  The party receiving my transfer imposes a time limit of 3 hours in which to complete a transaction.  I had previously sent smaller amounts that processed without a hitch.  These two transactions did not arrive before the 3-hour mark.  The system on the other end does not recognize my Tx IDs which is the only way to submit a help ticket, so I could not submit one.  

I have provided the data from the transactions section of my Monero GUI wallet and more data from XMRchain.  I'm just trying to be thorough, not knowing what all you would want to see.  The first transaction showed a recipient address earlier today (it had one showing since about 8 hours after the transaction was initiated, 5 days ago).  However, it now has gone back to saying "unknown recipient", just like the other transaction that is lost in limbo.  Both of these transactions were attempts at placing the same order two different times.  At the time I didn't realize that this money was just going to keep floating around in the blockchain and not come back to me on its own.  That was foolish lack of foresight on my part, and now I'm in danger of being short on rent next month if I can't figure this out.  I would really appreciate some help and guidance here.  Also would like to understand what happened and get some tips on avoiding this problem in the future.  I don't even know what caused it, but I'm trying to learn.  Thank you.

My Monero GUI Wallet Address for Reimbursement:
46DQdJLNSnsXEzsoJVzoYdeTym1RxdUCCYqt3ixw3YS1gLv7JcqsnQbLDVLQemBzztaPPe487NJCgYBftdqpnttxPJV8DZw
--------------------------------------------------
Transaction #1  (The most recent)

data from my wallet:

Fee:  0.00047831 XMR
Confirmations:  4206 (as of now, and still increasing)
Blockheight:  2296569

Tx ID:
e35c52870f7cf4d74f0618ccd57ae1e28404a44f8b530a0f055fe433c668ed7f
Date:
2021-02-14 03:05:57
Amount:
0.578778135048 XMR
Address:
46DQdJLNSnsXEzsoJVzoYdeTym1RxdUCCYqt3ixw3YS1gLv7JcqsnQbLDVLQemBzztaPPe487NJCgYBftdqpnttxPJV8DZw
Rings:
fdfe000e575e8732f40f0feba0c9470e47974f0c1f26ce4e430772b2665a029e absolute 16701994 26290081 26832137 26918618 27238388 27242799 27251660 27259923 27261825 27264995 27265771 fb1696777aceec9bac4ea5ef48d8c6d6e0dc23bcf10383f09c73a1b7027c1f59 absolute 21946535 27004330 27033431 27203896 27216056 27244089 27257494 27258528 27259454 27260152 27261110 45a568219156338af5f0b801c7af5ff1aa462dd63e9a279bdac8359e872f16c1 absolute 24261633 26017200 27066893 27193554 27237082 27246389 27246946 27254760 27263070 27263953 27264997

Payment Proof:
SpendProofV1HHQEngYkexGWgma9g85ivr3Txjicg9xKPaTKoqDdYY1T8FuFqrujjdNWsB9cA6kpmZ2LApQhXpAmGFPqY9be6oHLExyiWu13kqtDecVNKMthZbJ3LkaQ14HGS8PhBZkCgVx2VLxaZLLcwXpjaNk2ZxF1muaGQ7KBNYyuXHA7SwGS3bEH7aXuByqjrz2SY2vGzVKibe5kxrcCGVzrMWXj5YBi1WZV4R97V9xkZcE34TcpD7hc5nWev3rGLGdBpAfL2WnyH1r8bWZ5WUB2vq6anKbTu2TnUCNG4g1iENLKc4xfZ3DqciDSQUDEnGpGwbPNfG2Co8AhbvJuZLUKTg7Sn9HsK7bksyJBHoaFsraQwGeBZnorRLM1rrAfAHVbvjgyTL3zTzQrsYAcVXdncQtuUR61w82EF8JyGHe4dq5dggZK9LJ7rmV1G5Yaf6qEfVzrKd6j7FPwPfuM72VRHdyrSnJk78NyiG2eWp498WUQcfg5mnP32HhhBGugyA9vYSSEGXUs2Xsrq4Taq7Rk2DTE5367goK1mzh3pBbJ2QUyJTHuNuVbz4ZEi2EwK5Zp5U4PPf4imvCMDdWzMSUWcB6noftzpXdN3Ggve3PTKeMVGc7y8FxWUhiTnV7L9zeKdXM6jsxZWAkuiDCBzX6ybjvpFXgeEcK5ddMGiHyoaGEdK2ZhnqjcwwKNBPstvzxrg9WA81CNgcTkBtGgmzwFjVUY9YJR2TW5TeKk538L1P3vRfDiUvbEzANdYrucDiuVnjcJ7iSkruRaaivSD8C1FVCMHuTr37D9kzKser1YRLUmgMh9Xx3YmoYFvA8nj9uNxwVo8513gZtN5JWAAJKRknEU1CH5Nm7R2anG9FtPASBE6ZsUhTCnDxGUQCTJVSp6aBc725CaJC5jkK4o521wbY7t8K77kEneh53cRLzXKD6MyqYZ421HvEKWJizKFkZadYknjC9arAB2bt7ptBWCJo32G7a5QrQycdTMy7bLUwFw9jaDeAKeLPMeJV6dcwrX3PAiKCedfjV2CVb4drSsyKVnK7TYZuGAnp2uPQ8U4Wi5Bcbh1FmfwSAcas4Vhqfd9PsitVczNuuqGvvzfiD8c9Ay4TYPc8mj1QDhZ9dhqPpnbAB4sAYpNBSQ9x9pRmmdHhhEyXUBtyGXB3jbRMd5ps2snSDg7c9WKEGzH26Ji9gSTfYMU6eHuEGgtn7Qz7bKteqj7bqKnSi7C98YKQhRNenKtp3K8jFDJYagH3fF6taETmFcbTkwfVDeCJrZY37eKYGxpF16CP57CRL5hHG3zgKqDPLVSqrdNCs2oS52dVtM7KJKd2jf8dCPcjQU8KcKGaMUS28zBssyFa7ZT8emqKBWgz9tUbnTgzrDBuaVNqX78FMgatkQavVxr4VAzAZoTMeiSAQu2QqcQLXMLsbscYs5XpK91CMAZZP3CTfw7iypsxUtSQAFU77HjihBApb9iEoHefA64Mm2LXHpWQsTxqmfq3JAZBTDUEBQq3nFuVppLXkFzbTYhNDYgQjgZ4vPG1F4RiqyDirK2aajDQRNVT214PNRWUjFW2CzE1Kg6ZPy9TmKa6Tg59cCnubjBQYNhY4P1phrnm3CXDuG5ceurZ4vJcBUme4LT8yDPybqoaEDweaJprWnT5QY7GAF7Lnyr1uXq65KKwyN3Nft1yTU71DfSAJyM3hsxdWPceEZkeQyTSjDFkEVW3CKJSiUgEo5PR1A7AGWgKYijYM65wW4ENwJcHQJQrHhtDrBVBvC4MvtmTkhHm9HqprsiS1rqMZzfz9ewee6ftRnauJcLr5V3HtMTsmfWwZYPNdRwPDABZfaikSEJFh1HH82PKxjfzSxqUfFNfySaydpYzxxMG9SJDm62gSE3JacpQoMSarTepksFJRLbmaK2R8FzWNcFbMwCZ3EXzt3uM8ivtsJLDfzHV9t1V3LZRWSSuFEMc1aNy2kQDWQF8AL8CLMqqe5rRW9CBapej1xK96T5AhvP8kzjNEfCKZXCVaAmeMu2kEHAT81a9L9YqQ3Bb5f1KGKy1h1xnR3YPtPtHBaX2ehTDmYTq8sRZwq98rLQdEdPWtqFQnojsdvtNkzjkJV2CQankdFv81jXDwD9kFhv9T1qEPWpX1A6nGqTDKqRen47QEXDkD47eVMXwFXWx3hnwcAwDQpuDEkaq7D4TQgbsWNgFBJ6jow9dMMMjp4nxdh6enVKHdb8d4msgb4q5NVzfhhC7AiDwnncm54YSfhtwuz8BS2hQ8nmEb8gfi4zsNCRjQLg56KcxAx3ijbGs5gLCTgoxSTWuDtbpCjtq8H6EnZrV2sdW6ghtS7eG2jVUDbryQhgrnFu5xvkmK7NPfNo7XXYVirwiH4Fh98ZjSAj7pNhuVyosBbkzPnevqMZy1REgCLZTXUDcEW3wJ8LMSAesDV87rSLC3dBcJazMosZoAFhzeeGKJphLwhUAKJNaA7Y7xhCSCjEg5VG1CoUd1cJdc1xtZep9X44EViuiskbBPfYowSd569qvnijHHB5QJD8mjhn3XpQAmNRFqaTdCGTt9sW1Hzvpv6XPzQExA4jZe6UYgkUGDQNcNvsSniiZT3xZA8EwGQxQUdVArhXSDv8bNUCBCempXPL3NtJTXLRk4ZrahLZM9E4erAFvpDUPufE9t88dbn7WyNms2T6SymZWkagMz24DWk4nvXwxDAhow2PoyntPTf3hPsTb1AkN2HhEtcq3gLBLc1URuuaJQFs451EPSPHRExZyPU4jQu9ZTgWpBmF9eNgdQZS4e5r1XhHHvQgr1p3ZgZyVZQmK5G4Abuv8i3xGiADMJhrEzUDEHRYR5ygaU2tsg35USQqTmZoMDWrU2RLodFPnwyD6XPhejYgKyQ3jPQRAJBJoHWLnUwX4S42uTn5cT3

More info from XMRChain:

Tx hash: e35c52870f7cf4d74f0618ccd57ae1e28404a44f8b530a0f055fe433c668ed7f
Tx prefix hash: 7e5ef3225dbbe976899739a5d8fd9772ef0ec03c76b8dbadb71b070c52dec819
Tx public key: fe7f0ea28aa24924d951049a95f8b156af9a44adb58f58671fdbe72eb9e483b9
Payment id (encrypted): 79d70f226bc4ec73

Timestamp: 1613297157 
Timestamp [UCT]: 2021-02-14 10:05:57 
Age [y:d:h:m:s]: 00:005:20:03:24
-- | -- | --
Block: 2296569 
Fee (per_kB): 0.000478310000 (0.000197734937) 
Tx size: 2.4189 kB
Tx version: 2 
No of confirmations: 4200 
RingCT/type: yes/5
Extra: 01fe7f0ea28aa24924d951049a95f8b156af9a44adb58f58671fdbe72eb9e483b902090179d70f226bc4ec73

OUTPUTS:
stealth address                                                                                                         | amount |      amount idx
-- | -- | --
00: 436324b7efc5e56fb4859a32c3688e176702469efb64343bc7c0ba4126a82c86      | ? |             27266824 of 27520927
01: ff0a912ff44b491423e341db2376bf0e77b1fd88030012df2b1e59d8754552e6       | ? |             27266825 of 27520927

-----------------------------------
Transaction #2 (Placed earlier than #1):

data from my wallet:

Fee:  0.00013549 XMR
Confirmations:  4561 (as of now and still increasing)
Blockheight:  2296214

Tx ID:
069774119565605f1d4bfd81ec82eb257b998eba0fbe7b79ba68f6b51a5ce4be
Date:
2021-02-13 15:40:58
Amount:
0.56449926824 XMR
Address:
46DQdJLNSnsXEzsoJVzoYdeTym1RxdUCCYqt3ixw3YS1gLv7JcqsnQbLDVLQemBzztaPPe487NJCgYBftdqpnttxPJV8DZw
Rings:
f6cce0e4717d13291fbc82e04159d8dda8befe413c5f30129a902928bcef3dc9 absolute 4790833 21174556 27041551 27105156 27140301 27188183 27211038 27224746 27236357 27239664 27241593 f3bdd60d2ca98d724466bf38e2c999553faa5c1dc682d0315f5dc71344e139c8 absolute 17922839 26947495 26999031 27088995 27129646 27158365 27183223 27193823 27229195 27243012 27245030 c52524f3c2b7b2c4c4deddb138239189db052210a861892d4cee7b33b5dbe2d7 absolute 11257415 26402098 27033805 27216383 27226224 27227920 27231073 27243768 27244078 27245011 27245028 b2b1b2c01f1e37338effbb5011e23cab02d393c0ccfc2c18e1155f1d765b8cd4 absolute 22370065 26927718 27005775 27016060 27147546 27165888 27184404 27209755 27237689 27240422 27245870 407f1baa8907e36a0d86c282e0ae45bc1f58ad7c279c73c1e482f672a48aa643 absolute 24576909 26344922 27183557 27187080 27236113 27238765 27240519 27241341 27244272 27244742 27245197

Payment Proof:

SpendProofV1bX17gkHLeKLJC88jCWtdvA3kAXXwWCEv3Xhp1dXoc33tX2PEWYGDxhgaSnFZk5vhenFDbca9ofp8ZdE8vhKq36FSdwhsuqwNPWPPyVPyaFDta1ipHmBg9hypGXUTE4rZM1v6ZT48Lvs9CWKS8vwd2LSAeiEogg3DkZokZV6tx8vLmmZednpFwzTv4dQGykFXRsaaeB3DqD3Chugcj3bx47RV6tdtXCWCfsWECgCNimD8ArsRut28hJXf1VhYhBAzqrDrABe2PhZCw1dhpaK133NarurLZVLmcuTjcDdrY7XrUk3DNA26X4cYNV9BVuQTaUrfLVTqLLZSPW2jA6YEWcTUff5opF9BXQL2wyiERTMAP3WvC1kcoJ7HBBwyJAsX36Pr41mgkn3URFEPHWjik8YCEUP8WSSBoi5yjDZdeEVWw5hwktnX64Gr42G2vnj7xAwP7qFMJxSN6D7fHMnhXRMgvRTsPEbz3Y2Pi2qbR1rMj4ZTuB8TaMNR72gT1rGcD488EFk7UstFRJ66GwXaiDNkT9dYGwvbwDMes4dsRPyKEHTkCTEqkJoiQ4E8M2GWtPbiQUDgXA9P2M8REc8Lf1th3yw1m2gjiajiqpnhU4nR8J5cPQW5fDY53gbhfdWU9gqzqu9mJNFUqPf7sSEf5PCTn3n93pniJHPdC9xEhhRBdmVNkiNwAPKQkJaqhmAmSZQEcDC4SDNHHZuVuipgqdeJFJroWbtHKa5X2wrgVNCiZ5X3EUWxkfbFBUz7qeJ73oBd5GuBf6jYnipAtp2hkFNpdaD3tgQLeh9HRNX3mfbjxARVuZhPd9cbTYHWRSxu2eNAGydmLGP1SDdTbfYtzNYjNaFo4Dga1HkNAUb45g43jUDw2fFwcknkusSHrLHAvusojxP6uJTNfMUfjGrHL1fTBjSEdy9QuEnDuxNUXQpBC4Df3rZsHN6wWtWPAg8nt6pgUC8aBAx5CyjWkXk4tFGuxrHGag6kdKc3noEst4M7HmouJsQdPSe4idZYsmijmPsBcRUq595ac5LygSZ74DfmPf7eCv2PSr2QsHYkZchRpZXhyEC4byDubKRTvrQ4s6i9nSrkBBzKEf4vDaytJar5e5nCjX2FXXeNqapFfV1XNimajXysRbDiL9skoL7gcZXGHHH4FWeUwte4Bcbpp13SwAEqGoawTTQY4wVoB5G3u6WRtzdT3FGQ5aaxnmU2mmEwUdmhhUbekd53S21xdXTJMhmYyzhcyVN1n7UMeUhUKTJBzRaN1EzCzMb5XK8htTA7ACfaQLpNPiPxh1V245VbxYznSUAKNBdmUgckM3ijMc2djNYVaeAZjTHFFkUCyaeQR6jLQEXWRgNiMurKgD4CcAZeKaHLfNoXzg4JCmMVyu3qnzEeK6aMEwZAGWmLEenjSmzQ4oXQ2FpzTAe7U98ySKyD7RFmpH7FnQoByC1T3VFuRuSqWY258SycA5WJKiMxBYSvsscWJKNBuEDSe1gS9RfrajnZXCRfPLJr5ASTpSHRCEfdNUk5tCTMfG5t5qKfiBrg58oEjxMC3DvZWTNmTGBS6Xz3G48roBPTW4rBZKELgK2TcbFNNNYWS8H8bxcZxnXc7q7riGuorCN6MWk1Yk5PNwzmmMSdR8gF1DiU5ccp8v6SRJTyMPLQ3GEdtP4y6zkVRpg4RTzrmuZGoHft9dAGChQnQGoszhx7wSwA2cSsTQWiVUwnecg7FVd9YHPrN38iV9RyPQiNmi6S61ciJGvwuPA9Jp6ub9AqwYce4qr13zYDQ74BQWA48GW55bFdpeY7cy1sNTab5eKnXpL8HYXHvpDrUq5x9rdgdkiq4LawEhFDCPvqE9FAM1pcC8xCjd28v7TNqHGpNk298zKQdZsNW39nPgi9RrxAb8HhuuriJUYTwf8yCzTNojsHVztDzSVihifMEMJFSqgbWn2dBTEjUWmLdCnTFzWQhP3ZLUqxQ8Byt5AuvVsVhN29RLtnZanVefrFkhVUaB7aFr16G5ipAc59N8zFXSK2WN2FWkbTCkMecEabxg8TQbWE5VbLCDBwuKkGkDwdnko771j3YsBvJqDFY1kF9ab8ASTHLvQK2dbHidhvC2GEUE5WJwsRrHKh4RcTmZKuiYdBaZDYz99HYH6vbXcSCAQMAWKSf28TJMnhgZjcG2fQVWKSm3XJ9dcokRy1PQx8KN3hSg8Cac9nqjMHRkTgqj678X4J1pfc66FQk3kf4FNTKHiKc1phPtGn5QdM6W449YPcRGrFv6Rx6tbdWpof2Ahyi64xDu4N6pos8tdfvPx7VfNGMRRxyiXY2mxPpkgXo4UDWeqfwXdQRWZ6wU2HGbDiYGBFgB6oNH4iqJHoR2qSfYHnJn3tk9Jm8kdrKD543cXPYwxWiguh6RbWDm1LcBHmvE4KpaPQpjycSwqBib52TFkjeGMHjf3pRzEaJVoRutVpw83RGJkv5MMXR6e5wN65ST7BmXiGGnMcCp8fNc41igbzRZeTqQtumGvnHBQ58KJY4e8B5EwQ9FBsBY2w3MqcXU9b1cpgN1QxM5ThR3gZSZFK9519Hjd6BCBbwHQHenzAJbaBthAu693rceaQNKSAWJG8uE4J3HNSygAWJNgpWuyCCKBn9Fz5epeDBfTPPuEvmsueHtdXmJkcQxSrnSFgAbtDpTZh3NKJTAumUVLFYJ8MGAnKRtqA3WjZxrrWa4JmcPrLaAZX3ghNiSU1Xybf7joqbgpXHtLgUCDEdLFwWy48xkwcrq9eAdRT1Mk3N7bz71qHuVcbq6KCvTC9wDrGB8AQvTJ3uaiKB9ZDLYMNk2quKbjJxtMqV4pKazqbipJtsUeywNFy3CGZoVvnZnaoWs8djJ6z1tSy8QmA9UjVctQbHW7C1wvcopPUYQ2Te3peBiY38mzuDNpEVUQNTnUx2xvMNWEqWnT3kYa7B6fFdzsqt6DXNuHmJcMWtiffoD1avvymaCbXsERWe7j9qDjiXeVpvbw8Gw2awWkLk98TE4wfBFHCphAK7hQ5xnJsN7gpNL527vSdfDkTRQoxNeRhJsZvWde655fSG6U2Gp7Sr9wq4uzUyX27c9Fev911VFmjSfB77dbJucZpDTVd44tmgdLUpx69e3AM9CfhhrLps2ZHKfbYw3N4kr5TzXEnhydQXTpDv2ex58YTPZkjsSwx7bDGe5kWUVzmqm6FMnEwLWhUGJejRdifE89y9A4D9bShRL4GUEjLFmHWRrg6ww5dAxtWyHWpy9CxkCZzgisLbxNhEQrHpXm6dGyTXUNkqMP4rvC6EfeE7muzCsrYDxoqSmcvpkxYp3rS27giwbTBsUgkdvVAwhETdxKy4X4qbQE1z2gcmeWDVxrDM7CHJjE8BMGXqNqyjcnPZXdrFcbiC6G4ZHkfCJUTkbGDMzrfaTV37yhi5CsHBKn1cmoCP8ar7fiaJ3UkfBu3ERpyTNzKjgE253zktAEa1BD1ADzX9V9E5kTjjMrqvCpLu2q8yp8dQ67K4MPUPXZCSPYPPwbDofP47tNEdMPCcWf7UjzUvymAhvA8XWGJPbmavE7YTiV1BrkTKRt21wwtZnkW8fJxDoUMuQ4KtqCx5SrD5Nv74Z2KJDGFLwcDSNhNNnG9UxNLCTRCa4MnZdBqJF1zG7oBJS8RD4EkVpWvTH8ajssAnsvUeJdvhmbJLnV6iVqQuP2eZ2BKeKPNg74XfqELmeXKTq4rGM7KfALSUMmmVGSY58zUKJ2SdEKLTtQ6ttALkN5Xje79GmSvJwLDctsFDdmj5UAaK5DSGMbXU1SbiSjNqWrTpphScmbBkDQgHEth57Pr9dPWQmpPmoo9RJ1Hpi4qMuFAeRwE4GxyP32XLML8zUFQraVPAp9exexrBBk8gBiaKn19ACRMjfqeWbJEveFNbhCFZMv7RLvQSbvCHG9KuQu1f42cjFGZ1f2qBZ7kGCpAZiuvJRygjb1xVPWCDZckk85gd2SBy5qDXVcT9m5oTpKhmoXZEDeS5WPzGeJFhMwAVXyk81BS8ixD5TAYXo42UXKjRQWPACRGZhyyBveaQ5TwL3jFRG3DeBDDQK3JTm4JKanrdkjcUBfC5SAKUnGTQhCF8e1HTdw9TPRzC2kSnn3xkn2eZuRM4CB2n6L1enZKWmqszyPaJhwc3eNJYnxz57dxsCjp6A5SJbEAtu9SqK547hkE552kBAhKN4ndhWZtiWV8FmcYR4h6ybFg1yYbUmrB79tg4iV5JzzKkHwuidiAeS9EYyDoKXZwgfpRG56AbUWpPcMGQeHoYbeEjS5DboxAxw3QoMm8DrBcD3sLyTJsnYBT7wK5SJezgUNdhrabaNT6uPf6EX9eg9Gj94WG9j4DCCjaBCk1k5y4Xpg7k7KMEdaXTABhSDGbvUC9MHq37mBpULkqUFhh7FCiuEX6BR3kPEXTzfad59h14iEmqBtPXyQQo9NjaNgSRcH1QVvZCAWW49LTmFGDhVNfDvS6L67Fj6JPmjqaSSFZ2vKiYbQJaXfDEstw8DTtTqCPoEhnfX8hBDz95UePMzkNq1uzYFw5YYwKSea1mdd1wfW9wcbmtYhJ7eTcCKmVFakQLJcN7RtZGGKhs4sryj51BxU2hgiZQ5zR8nNX5Nb89Gc7nydp2rM9oemAJZ9XPPEvFF821b91gZCx8wRC5zasQivg7J6yY8T8WVHjShDcEajUbxxJR1nW1LeKzTTopte9ESSsdQJoWuKahBUDohwaJkhMBAc9MPFeVVQNXprDEdbPNYvcJiQeqjRFWknxGRbUdRBx6q22MM5dLDBuCkfWRL8wN2api8xq2CVMobmMuU6DZVDB9dQagQ81Wfac5mL2Gghq

more info from XMRChain:

Tx hash: 069774119565605f1d4bfd81ec82eb257b998eba0fbe7b79ba68f6b51a5ce4be
Tx prefix hash: 39dccc6aa1d259c1171244886604a5abe52c6b40aca673862b76954b30b20c3b
Tx public key: 203da274e48e0c9339dbf3747bae5e8944e38e9936d3f8e2554b996e884a270e
Payment id (encrypted): 901bd3060ad704b1

Timestamp: 1613256058 
Timestamp [UCT]: 2021-02-13 22:40:58 
Age [y:d:h:m:s]: 00:006:07:34:36
-- | -- | --
Block: 2296214 
Fee (per_kB): 0.000135490000 (0.000039572664) 
Tx size: 3.4238 kB
Tx version: 2 
No of confirmations: 4557 
RingCT/type: yes/5
Extra: 01203da274e48e0c9339dbf3747bae5e8944e38e9936d3f8e2554b996e884a270e020901901bd3060ad704b1

OUTPUTS:
stealth address                                                                                                         | amount |      amount idx
-- | -- | --

00: 4b1fe7aa0e91a2d98d3933195c2edb8184ca8b3517a65e49c65ef011883bf28b       | ? |            27246389 of 27521014
01: 39dd2bc5cc16a2dfc9465eb90456620100234936fb42f61e9e54afd1e7b8f529         | ? |            27246390 of 27521014

---------------------------

Thank you for your time and effort.  Any guidance/assistance greatly appreciated.

**Comment by rating89us** [comment] 2021-02-20 12:45
Your transaction was confirmed and definitely the recipient received your money. You should contact them and ask the recipient (not us) for reimbursement. If they say they never received your payment, you're probably a victim of a scam. 

Since criptocurrency transactions are irreversible, there is not nothing we can do to help you. Next time you should investigate better the recipient reputation and/or at least use an escrow account with a trusted third-party.

**Comment by dustyheals** [comment] 2021-02-20 19:15
Ok.  However, I have reason to believe this is not the case.  I was
watching the transaction on XMRChain the moment after I sent it.  The
confirmations were just climbing up and up and they still are as of today.
Furthermore, my wallet says "unknown recipient" instead giving the
recipient's XMR address like it usually does once it is completed.  I could
see that it had not finished processing by the 3 hour mark and I watched
the exchange cancel the order as that time light was exceeded.  The
exchange has no reason to deny that the transfer came through.  They
validated the other ones.  Also, on this exchange, even after the
transactions go through, the funds are held in Escrow until the vendor
fulfills their end of the agreement and then I finalize the transfer.  That
feature is automatic.  I sent th transfer to the exchange, not to
the vendor.  This exchange is known for running a tight ship and
prioritizing security. But the most telling thing to me is that when I look
at the transaction in my wallet or on XMRchain, it is still being
confirmed.  If a transaction completes successfully, wouldn't it stop
adding confirmations?  These have not stopped..  They just keep gaining
more confirmations.  Am I wrong?  Is that not a relevant observation?  Do
some transactions just keep confirming forever?  I have others that went
through successfully and they don't keep getting confirmed like these two.
Maybe I'm wrong.  I'd be happy to hear the explanation.  I can't be the
only person who has experienced this issue.  One of my two transactions,
the first one that I listed, it did look like it completed about 9 hours
later than I needed it to.  It showed a recipient address.  But then, a few
days later, that address changed back to "unknown recipient" in my wallet.
My assumption is that they reject any transactions that take longer than
three hours.  Is that something a recipient can do?  Can a transaction be
rejected by the receiver?  If so, what happens to it then?  Since they make
a point of limiting the time window to 3 hours and canceling the order as
soon as that limit is reached, I would think that transactions are rejected
by them on a regular basis, possibly as an automatic function of their
software.  I made purchases with 3 vendors that day.

I am grateful to you for replying to my inquiry.  Since I cannot open a
help ticket on the exchange if my Tx ID is not in their system, I guess I
shall try to contact them on the subbredit.

You mentioned using an escrow account with a trusted third party.  I had
assumed that that's what I was doing because of how the system is set up.
Is there an external escrow service I can utilizee instead of relying on
the exchange to hold my funds until finalized?  Is that an option available
to me?  How would I find this third party and request them to do this for
me?

**Comment by rating89us** [comment] 2021-02-20 21:20
> The confirmations were just climbing up and up and they still are as of today.
> ...when I look at the transaction in my wallet or on XMRchain, it is still being
confirmed.

This is expected behavior when a transaction is sucessfully sent. Since your transaction has 4557 confirmations, it means that 4556 blocks were mined after the block that included your transaction, so it was definitely sent (it takes ~2 minutes for each block to be mined).

>  I have others that went through successfully and they don't keep getting confirmed like these two.

This behavior is not expected. Once confirmed, a succesful transaction should add new confirmations forever.

> Furthermore, my wallet says "unknown recipient" instead giving the recipient's XMR address like it usually does once it is completed. 
>  One of my two transactions, the first one that I listed, it did look like it completed about 9 hours later than I needed it to.  It showed a recipient address.  But then, a few
days later, that address changed back to "unknown recipient" in my wallet.

If your wallet displays "unknown recipient" after some time, it means it lost this information, which is stored in its cache file. Monero GUI wallet always saves the destination address of each transaction in its cache. Usually what makes the wallet lose its cache file is restoring/refreshing the wallet from seed or changing wallet restore height.

Which Monero wallet did you use to send these transactions? Was it GUI wallet?
If so, did you refresh/recover your wallet from seed after sending these transactions?
If you're not using GUI wallet, and for instance, is using cake wallet in mobile, you need to activate in settings page the option to save destination addresses.

> The exchange has no reason to deny that the transfer came through. They validated the other ones. 

All cryptocurrency scammers work this way: first they do 1, 2 or 3 successful transactions to gain customer confidence, then, when you do a larger transaction, they get your money and disappear.


> My assumption is that they reject any transactions that take longer than three hours.  Is that something a recipient can do?  Can a transaction be rejected by the receiver? 

They can rejected the transaction in their system (and refuse to do the exchange) because the exchange rate is not updated after some time. But since it's not possible to reject a transaction in the monero protocol, it's not possible for a monero wallet to decline receiving funds. If you sent them a transaction and the transaction was confirmed, your funds are now in their wallet. Cryptocurrency transactions are atomic, that means that the funds are either in the wallet of the sender or in the wallet of the receiver, they don't stay in a temporary place between both wallets.

If the exchange is honest, they should refund you once you paid them and received nothing in return. You should contact them, but there is nothing we can do to help you in this sense (the fund is already in their wallet and transactions are irreversible). If you still have the destination address of the transaction (maybe you can recover it from the exchange website), you will be able to prove to the exchange that you sent them these transactions. You can use this tool (https://www.exploremonero.com/receipt), just fill with the transaction id, the destination address and the transaction key (you can find this in History page if you use Monero GUI wallet).

> You mentioned using an escrow account with a trusted third party.  I had
assumed that that's what I was doing because of how the system is set up. 

No, what you did was paying directly to someone else's wallet. 

> Is there an external escrow service I can utilizee instead of relying on the exchange to hold my funds until finalized?  

A multisignature transaction is a transaction that needs multiple signatures to be send (like 2-of-3 signatures). So there are 3 users (and 3 keys) involved in the transaction: the buyer, the seller and an arbiter. You can see this type of scheme when using exchanges like https://bisq.network/ to do exchanges.

**Comment by dustyheals** [comment] 2021-02-21 04:34
Alright.  Thank you for the all this info.  It's a big help.

But one last thing I must note.  I have sent myself XMR transactions from
one wallet to the other... (as in Cake to GUI) .  Never has it gone through
in two minutes..  Not even close.  Cake was horrifically slow, sending to
Monero GUI Wallet.  .I even had transactions that I sent to myself from
Cake not go through to meal at all, and get lost in limbo just like the
transactions in my original post that were sent to the onion exchange.  One
of them actually did come back to the Cake wallet eventually I believe.  So
this idea that XMR travels fast and cannot be reversed does not measure up
at all with my experiences so far.

Sending Bitcoin to ChangeNOW.io to swap it for XMR with my Monero GUI
Wallet as the final destination, originating from my Coinbase and CashApp
accounts.... those came to be the only XMR involved transactions
that completed in a reasonable time.  They were the fastest, but not
actually "Fast".  Just the fastest movement I was able to observe that
involved XMR.  Nothing about Monero has been anything close to 2-minute
fast.

The only crypto that's moved at a pace that I could consider to be fast and
efficient are the BTC transfers that I've sent from CashApp.  Coinbase is a
fairly quick runner up.  Coinbase is much better  these days but they used
to take forever.  I stopped using them for years partly due to this
reason.  They're a lot better now.,  I just recently started using Coinbase
again. . They have definitely made a lot of improvements, Even still, it
was nowhere near 2 minutes.

What can I do to  make transactions happen quickly the way you claim they
are?  And by that, I'm not including the answer that the transfer happens
in two minutes but just doesn't get updated by the wallets until much
later.  I'm not interested in that logic.  If that is the case, then what
I'm trying to find out is what I can do to make the wallet process
quicker..  That's the only completion that actually counts.  The point at
which the recipient can validate that they received the money...

In that sense, are there really Monero Spends that only take two minutes?
If so, what measures can I implement to get mine to happen quicker?.

I started over in my attempts to form a node instead of using public.  It's
been downloading for a couple days, and its almost 40%.  Seems to be going
a little quicker than last time, thankfully..

Once I get to use my own local node, should that

**Comment by dustyheals** [comment] 2021-02-21 04:37
Should that hasten and smooth things out at my end, theoretically?  Having
a local node would add stability, I'm hoping.

**Comment by JustFranz** [comment] 2021-02-23 06:26
The XMR will arrive in the recipent wallet as soon as a miner has included your transaction in a block that they mined. Monero blocks are mined every 2 minutes and since Monero blocks are not full it should not take more than 2 minutes to get a confirmation.

If a transaction is sent but gets dropped then what likely happened is a node dropped your transaction in the Dandelion++ stem phase. Dandelion++ is a technology that helps obfuscate the origin IP of a Monero transaction. If that happens then send the transaction again. I am not aware of an active attack on the Monero network that is maliciously dropping transactions, it could happen at any time though.

A Monero transaction should not take more than 2 minutes. For you to see the transaction you need to verify the blockchain from the point you last stopped verifying. Depending on when that was it can take quite a while. In the case of a remote node you need to scan all the transactions for ones that are meant for you, that can take a while. The timestamp of the first confirmation is when the Monero arrived in the receiving wallet. If there is a delay between that and you seeing it in your wallet then the problem is your wallet. It is either not synced, is not syncing at all, you are not connected to a remote node in the first place or your wallet restore height is set to after the first confirmation of the transaction.

Or your seed is compromised and the money was already sent out, that can happen too. Never use web wallets, never generate a seed on a website and never give out your seed. Use a secure computer and operating system to safeguard your money.

I've experienced in the past where the Official GUI will stop syncing, freeze, not indicate what it is doing, won't tell you when a remote node is down and other annoyances.

Try out the Feather Wallet, it is light weight and easier to use. featherwallet dot org is the address. The development was funded by the Monero community and you can trust the software.


Those two transactions that you sent went through. Contact them about all the details for support. If they deny receiving them then you got scammed.

The Monero devs or devs of any decentralized cryptocurrency can not reverse or refund transactions. They just make the software. You own and are responsible for your coins.

**Comment by selsta** [comment] 2021-03-11 23:35
Closing as the reported issue does not seem GUI specific.

**Closed by selsta** 2021-03-11 23:35 UTC
