### ISSUE TITLE
Cannot connect to network v0.12 Linux

### ISSUE THREAD

**Issue by vasecthomas** [monero-project/monero-gui#1310] opened 2018-04-12 08:53 UTC
I'm having trouble finding resources on how to solve my problem. I cannot connect to the network and the daemon will not start. 

![screenshot at 2018-04-12 01-51-39](https://user-images.githubusercontent.com/4716955/38666612-e0f7e0f4-3e2e-11e8-8827-291ce1c2851d.png)
![screenshot at 2018-04-12 01-51-51](https://user-images.githubusercontent.com/4716955/38666613-e11342f4-3e2e-11e8-9f77-c4f447623e75.png)

**Comment by dEBRUYNE-1** [comment] 2018-04-12 09:03
Duplicate of #1261. Also see:

https://monero.stackexchange.com/questions/7999/linux-gui-v0-12-does-not-connect-to-local-or-remote-node-stdbad-cast-error

**Comment by dEBRUYNE-1** [comment] 2018-07-04 08:39
This particular issue is resolved in GUI v0.12.2.0: 

https://www.reddit.com/r/Monero/comments/8vkx2g/gui_v01220_released/

**Comment by dEBRUYNE-1** [comment] 2018-07-04 08:39
+resolved

**Closed** 2018-07-04 09:45 UTC
Labels: resolved
