### ISSUE TITLE
New GUI release 13.0.3 does not open on mac sierra 10.13.6

### ISSUE THREAD

**Issue by Elcigno** [monero-project/monero-gui#1684] opened 2018-10-19 13:49 UTC
Hi,
as per title, it does not open asking to contact the developer.

Thank you in advance for your help.

**Comment by skftn** [comment] 2018-10-19 14:17
Duplicate of #1658. This particular issue will be fixed in GUI v0.13.0.4. In addition, a temporary workaround can be found here:

https://monero.stackexchange.com/questions/10364/gui-v0-13-0-3-does-not-start-on-mac-os-x-monero-wallet-gui-cannot-be-opened-bec

**Comment by skftn** [comment] 2018-10-19 14:17
+resolved

**Closed** 2018-10-19 14:18 UTC
Labels: resolved
